"""Model and properties emission at the sync fixed point (spec §5, §6).

Every emitted byte is deterministic from the two contracts plus
ENGINE_VERSION. SQL: payloads are ``lower(to_json(struct_pack(...)))``
with fields pre-sorted by lowercased name (sortedness is an emission-time
property, F-11), every value cast to VARCHAR, record keys ``sha256()``
computed in SQL uniformly; constant source and run payloads included.
Schema keys are Python literals via ``metricmine.keys.manifest_key``.
Properties YAML is emitted in sync's own canonical form (F-18) so gate 3
has nothing to rewrite (Q8/F-14): ``yaml.safe_dump`` with descriptions
parsed from folded ``>`` contract scalars forced single-quoted, the
sync-shaped ``not_null`` block per required column, and the ``unique:``
twin per single-column primaryKey (F-17; composite keys get none).
"""

from __future__ import annotations

import json

import yaml

from metricmine.engine import ENGINE_VERSION
from metricmine.keys import canonical_manifest, manifest_key

_SQL_HEADER = (
    "-- Generated by metricmine-engine v{engine} from {mapping_id}"
    " v{mapping_version} + {gold_id} v{gold_version}.\n"
    "-- Engine-owned (D-09): do not edit; flag drift instead (rule 8)."
    " Spec: docs/spec/engine.md.\n"
)
_YML_HEADER = (
    "# Generated by metricmine-engine v{engine} from {mapping_id}"
    " v{mapping_version} + {gold_id} v{gold_version}.\n"
    "# Engine-owned (D-09): do not edit; flag drift instead (rule 8)."
    " Spec: docs/spec/engine.md.\n"
)


class _FoldedStr(str):
    """A description parsed from a folded ``>`` contract scalar.

    Sync re-emits such descriptions single-quoted with the trailing
    newline stripped (F-18); forcing the style here keeps the emitted
    bytes at the fixed point.
    """


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(
    _FoldedStr,
    lambda dumper, value: dumper.represent_scalar(
        "tag:yaml.org,2002:str", str(value), style="'"
    ),
)


def _description(raw: str) -> str:
    if raw.endswith("\n"):
        return _FoldedStr(raw.rstrip("\n"))
    return raw


class Emission:
    """Parameter view over the validated contracts."""

    def __init__(
        self, mapping: dict, star: dict, materialization: str = "table"
    ) -> None:
        self.mapping = mapping
        self.star = star
        # D-38: `table` or `incremental`; validated fail-closed in emit.py.
        # The emitted SQL carries the is_incremental() blocks either way
        # (inert under table), so the two modes differ only in the config
        # line and a regeneration that flips modes diffs one line per model.
        self.materialization = materialization
        self.category = mapping["schema"][0]
        self.category_name = self.category["name"]
        self.source_table = self.category["sourceTable"]
        self.source_model = self.source_table.split(".", 1)[1]
        self.time_column = self.category["timeColumn"]
        self.time_grain = self.category["timeGrain"]
        self.header_args = {
            "engine": ENGINE_VERSION,
            "mapping_id": mapping["id"],
            "mapping_version": mapping["version"],
            "gold_id": star["id"],
            "gold_version": star["version"],
        }

        properties = self.category["properties"]
        self.dimension_fields = [
            p["name"] for p in properties if p["mappingRole"] == "dimension"
        ]
        self.measure_fields = [
            p["name"] for p in properties if p["mappingRole"] == "measure"
        ]
        self.derived_identifiers = [
            entry
            for entry in self.category["grain"].get("degenerateIdentifiers", [])
            if entry["source"] == "derived"
        ]
        carried = [
            entry["column"]
            for entry in self.category["grain"].get("degenerateIdentifiers", [])
            if entry["source"] == "column"
        ]
        self.dim_payload_columns = self.dimension_fields + [
            column for column in carried if column not in self.dimension_fields
        ]

        # Declared manifest orders (spec §3): dimension-role fields in
        # contract order with derived identifiers last; measures in
        # contract order; the star-global manifests are fixed.
        self.dim_manifest = self.dim_payload_columns + [
            entry["name"] for entry in self.derived_identifiers
        ]
        self.measure_manifest = list(self.measure_fields)
        self.source_manifest = ["source_table"]
        self.run_manifest = [
            "mapping_contract_name",
            "mapping_contract_version",
            "engine_version",
        ]
        self.timeframe_manifest = [self.time_column]

        self.dim_col_key = manifest_key(self.dim_manifest)
        self.fact_col_key = manifest_key(self.measure_manifest)
        self.source_col_key = manifest_key(self.source_manifest)
        self.run_col_key = manifest_key(self.run_manifest)
        self.timeframe_col_key = manifest_key(self.timeframe_manifest)

        self.run_entries = {
            "mapping_contract_name": f"'{mapping['id']}'",
            "mapping_contract_version": f"'{mapping['version']}'",
            "engine_version": f"'{ENGINE_VERSION}'",
        }

    def sql_header(self) -> str:
        return _SQL_HEADER.format(**self.header_args)

    def yml_header(self) -> str:
        return _YML_HEADER.format(**self.header_args)

    def config_line(self) -> str:
        """The explicit materialization config (D-38).

        Incremental adds on_schema_change='fail': dbt 1.12 requires it on
        contracted incremental models, and failing is the contract-first
        posture; a shape change arrives through the contract and a
        regeneration (D-08, D-09), never silently at build time.
        """
        if self.materialization == "incremental":
            return (
                "{{ config(materialized='incremental',"
                " on_schema_change='fail') }}"
            )
        return "{{ config(materialized='table') }}"


_SOURCE_BATCH_FILTER = """
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}"""


def _anti_join(key_equalities: str) -> str:
    """The insert-if-absent guard (D-38): inert under table; the global
    dedupe under incremental (content addressing makes the >= boundary
    re-scan idempotent)."""
    return f"""{{% if is_incremental() %}}
where not exists (
    select 1 from {{{{ this }}}} t
    where {key_equalities}
)
{{% endif %}}"""


def _struct_block(entries: dict[str, str], indent: int) -> str:
    """Render struct_pack member lines, fields sorted by lowercased name.

    ``entries`` maps field name to its SQL value expression; a multi-line
    expression (the nested derived-identifier payload) is indented four
    deeper than its member line by construction.
    """
    pad = " " * indent
    lines = [
        f"{pad}{name} := {expression}"
        for name, expression in sorted(
            entries.items(), key=lambda item: item[0].lower()
        )
    ]
    return ",\n".join(lines)


def _cast_entries(columns: list[str]) -> dict[str, str]:
    return {column: f"cast({column} as varchar)" for column in columns}


def _derived_expression(of_columns: list[str], indent: int) -> str:
    """The nested canonical payload of a derived degenerate identifier."""
    inner = _struct_block(_cast_entries(of_columns), indent + 4)
    pad = " " * indent
    return f"sha256(lower(to_json(struct_pack(\n{inner}\n{pad}))))"


def _dim_payload_entries(emission: Emission, indent: int) -> dict[str, str]:
    entries = _cast_entries(emission.dim_payload_columns)
    for identifier in emission.derived_identifiers:
        entries[identifier["name"]] = _derived_expression(
            identifier["of"], indent
        )
    return entries


def _timeframe_expression(emission: Emission) -> str:
    return (
        f"cast(date_trunc('{emission.time_grain}',"
        f" {emission.time_column}) as varchar)"
    )


def category_values_sql(emission: Emission) -> str:
    entries = _struct_block(_dim_payload_entries(emission, 12), 12)
    guard = _anti_join("t.dim_hash_id = sha256(grouped.dim_values)")
    return f"""{emission.sql_header()}
{emission.config_line()}

with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}{_SOURCE_BATCH_FILTER}

),

payloads as (

    select
        lower(to_json(struct_pack(
{entries}
        ))) as dim_values,
        captured_at
    from source

),

grouped as (

    select
        dim_values,
        min(captured_at) as captured_at
    from payloads
    group by dim_values

)

select
    sha256(dim_values)          as dim_hash_id,
    '{emission.dim_col_key}' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{guard}
"""


def category_columns_sql(emission: Emission) -> str:
    dim_manifest = canonical_manifest(emission.dim_manifest)
    measure_manifest = canonical_manifest(emission.measure_manifest)
    guard = _anti_join("t.dim_col_hash_id = manifests.dim_col_hash_id")
    return f"""{emission.sql_header()}
{emission.config_line()}

with manifests as (

    select '{dim_manifest}' as dim_columns, '{emission.dim_col_key}' as dim_col_hash_id
    union all
    select '{measure_manifest}', '{emission.fact_col_key}'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
{guard}
"""


def source_values_sql(emission: Emission) -> str:
    guard = _anti_join("t.source_hash_id = sha256(payload.source_values)")
    return f"""{emission.sql_header()}
{emission.config_line()}

with payload as (

    select lower(to_json(struct_pack(
            source_table := '{emission.source_table}'
        ))) as source_values

)

select
    sha256(source_values)      as source_hash_id,
    '{emission.source_col_key}' as source_col_hash_id,
    source_values,
    current_localtimestamp()    as loaded_at
from payload
{guard}
"""


def run_values_sql(emission: Emission) -> str:
    entries = _struct_block(emission.run_entries, 12)
    guard = _anti_join("t.run_hash_id = sha256(payload.run_values)")
    return f"""{emission.sql_header()}
{emission.config_line()}

with payload as (

    select lower(to_json(struct_pack(
{entries}
        ))) as run_values

)

select
    sha256(run_values)      as run_hash_id,
    '{emission.run_col_key}' as run_col_hash_id,
    run_values,
    current_localtimestamp()    as loaded_at
from payload
{guard}
"""


def timeframe_values_sql(emission: Emission) -> str:
    entry = f"{emission.time_column} := {_timeframe_expression(emission)}"
    guard = _anti_join(
        "t.timeframe_hash_id = sha256(grouped.timeframe_values)"
    )
    return f"""{emission.sql_header()}
{emission.config_line()}

with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}{_SOURCE_BATCH_FILTER}

),

payloads as (

    select
        lower(to_json(struct_pack(
            {entry}
        ))) as timeframe_values,
        captured_at
    from source

),

grouped as (

    select
        timeframe_values,
        min(captured_at) as captured_at
    from payloads
    group by timeframe_values

)

select
    sha256(timeframe_values)    as timeframe_hash_id,
    '{emission.timeframe_col_key}' as timeframe_col_hash_id,
    timeframe_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{guard}
"""


def _shared_columns_sql(
    emission: Emission, prefix: str, key: str, manifest: list[str]
) -> str:
    guard = _anti_join(
        f"t.{prefix}_col_hash_id = manifest.{prefix}_col_hash_id"
    )
    return f"""{emission.sql_header()}
{emission.config_line()}

with manifest as (

    select
        '{key}' as {prefix}_col_hash_id,
        '{canonical_manifest(manifest)}' as {prefix}_columns

)

select
    {prefix}_col_hash_id,
    {prefix}_columns,
    current_localtimestamp()    as loaded_at
from manifest
{guard}
"""


def source_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission, "source", emission.source_col_key, emission.source_manifest
    )


def run_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission, "run", emission.run_col_key, emission.run_manifest
    )


def timeframe_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission,
        "timeframe",
        emission.timeframe_col_key,
        emission.timeframe_manifest,
    )


def fact_values_sql(emission: Emission) -> str:
    measure_entries = _struct_block(_cast_entries(emission.measure_fields), 12)
    dim_entries = _struct_block(_dim_payload_entries(emission, 12), 12)
    timeframe_entry = (
        f"{emission.time_column} := {_timeframe_expression(emission)}"
    )
    source_entry = f"source_table := '{emission.source_table}'"
    run_entries_hashed = _struct_block(emission.run_entries, 16)
    guard = _anti_join(
        "t.fact_hash_id = hashed.fact_hash_id\n"
        "      and t.source_hash_id = hashed.source_hash_id\n"
        "      and t.timeframe_hash_id = hashed.timeframe_hash_id\n"
        "      and t.dim_hash_id = hashed.dim_hash_id"
    )
    return f"""{emission.sql_header()}
{emission.config_line()}

with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}{_SOURCE_BATCH_FILTER}

),

keyed as (

    select
        lower(to_json(struct_pack(
{measure_entries}
        ))) as fact_values,
        lower(to_json(struct_pack(
{dim_entries}
        ))) as dim_payload,
        lower(to_json(struct_pack(
            {timeframe_entry}
        ))) as timeframe_payload,
        captured_at
    from source

),

hashed as (

    select
        sha256(fact_values)         as fact_hash_id,
        sha256(lower(to_json(struct_pack(
                {source_entry}
            )))) as source_hash_id,
        sha256(timeframe_payload)   as timeframe_hash_id,
        sha256(dim_payload)         as dim_hash_id,
        sha256(lower(to_json(struct_pack(
{run_entries_hashed}
            )))) as run_hash_id,
        '{emission.fact_col_key}' as fact_col_hash_id,
        fact_values,
        captured_at
    from keyed

)

select
    fact_hash_id,
    source_hash_id,
    timeframe_hash_id,
    dim_hash_id,
    run_hash_id,
    fact_col_hash_id,
    fact_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from hashed
{guard}
"""


_DERIVATIVE_LABEL = (
    "Derivative typed projection over the star; uncontracted by design"
    " (D-17). Do not edit; flag drift instead (rule 8)."
)

_MART_LABEL = (
    "Derivative typed mart over the star; uncontracted by design"
    " (D-17 as amended by D-36). Do not edit; flag drift instead (rule 8)."
)


def registry_declared(star: dict) -> bool:
    """The extended-star activation switch (spec §5): the registry and the
    typed projection join the emission set once the gold contract declares
    the context_registry object."""
    return any(obj["name"] == "context_registry" for obj in star["schema"])


def context_json(compiled_context: dict) -> str:
    """Canonical compact JSON for a registry cell.

    Addressed content, never a hashed payload (D-19), so it is NOT
    lowercased; sorted keys and compact separators keep it deterministic.
    """
    return json.dumps(
        compiled_context,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _sql_string(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def registry_sql(emission: Emission, compiled: dict) -> str:
    """context_registry rows as VALUES literals carried from the
    compiled-context artifact (D-30): no build-time file reads, every
    warehouse write stays inside dbt build."""
    rows = ",\n".join(
        "        ("
        + ", ".join(
            _sql_string(cell)
            for cell in (
                entry["schema_key"],
                entry["entity_group"],
                entry["contract_name"],
                entry["contract_version"],
                context_json(entry["compiled_context"]),
            )
        )
        + ")"
        for entry in compiled["entries"]
    )
    guard = _anti_join("t.schema_key = rows.schema_key")
    return f"""{emission.sql_header()}
{emission.config_line()}

with rows as (

    select * from (values
{rows}
    ) as t (schema_key, entity_group, contract_name, contract_version, compiled_context)

)

select
    schema_key,
    entity_group,
    contract_name,
    contract_version,
    compiled_context,
    current_localtimestamp()    as loaded_at
from rows
{guard}
"""


def _projection_sql_header(emission: Emission) -> str:
    first_line = emission.sql_header().split("\n", 1)[0]
    return f"{first_line}\n-- {_DERIVATIVE_LABEL}\n"


def _projection_yml_header(emission: Emission) -> str:
    first_line = emission.yml_header().split("\n", 1)[0]
    return f"{first_line}\n# {_DERIVATIVE_LABEL}\n"


def projection_sql(emission: Emission) -> str:
    """vw_<category>_typed: json_extract plus cast per manifest field.

    Cast types are the mapping contract's physicalType verbatim; derived
    identifiers are VARCHAR (canonical hex text). The view config is
    explicit because the gold folder default is table.
    """
    physical_types = {
        prop["name"]: prop["physicalType"]
        for prop in emission.category["properties"]
    }
    fields = (
        [(name, "d.dim_values") for name in emission.dim_manifest]
        + [(name, "t.timeframe_values") for name in emission.timeframe_manifest]
        + [(name, "f.fact_values") for name in emission.measure_manifest]
    )
    select_lines = ",\n".join(
        f"    cast(json_extract_string({payload}, '$.{name}')"
        f" as {physical_types.get(name, 'VARCHAR')}) as {name}"
        for name, payload in fields
    )
    category = emission.category_name
    return f"""{_projection_sql_header(emission)}
{{{{ config(materialized='view') }}}}

with f as (

    select * from {{{{ ref('fact_{category}_values') }}}}

),

d as (

    select * from {{{{ ref('dim_{category}_values') }}}}

),

t as (

    select * from {{{{ ref('dim_timeframe_values') }}}}

)

select
{select_lines}
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
"""


def _mart_sql_header(emission: Emission) -> str:
    first_line = emission.sql_header().split("\n", 1)[0]
    return f"{first_line}\n-- {_MART_LABEL}\n"


def _mart_yml_header(emission: Emission) -> str:
    first_line = emission.yml_header().split("\n", 1)[0]
    return f"{first_line}\n# {_MART_LABEL}\n"


def mart_sql(emission: Emission) -> str:
    """mart_<category>_typed: the typed projection materialized as a table
    (D-36).

    Lean shape: the typed business columns (dimension payload columns,
    then the timeframe and measure manifests, cast per the mapping
    contract's physicalType exactly as the projection does) plus
    fact_hash_id as the provenance pointer back to the star. Derived
    identifiers stay inside the dimension payload and are not carried.
    Rows are ordered by the declared time column so zone maps prune
    time-window scans.
    """
    physical_types = {
        prop["name"]: prop["physicalType"]
        for prop in emission.category["properties"]
    }
    fields = (
        [(name, "d.dim_values") for name in emission.dim_payload_columns]
        + [(name, "t.timeframe_values") for name in emission.timeframe_manifest]
        + [(name, "f.fact_values") for name in emission.measure_manifest]
    )
    select_lines = ",\n".join(
        f"    cast(json_extract_string({payload}, '$.{name}')"
        f" as {physical_types.get(name, 'VARCHAR')}) as {name}"
        for name, payload in fields
    )
    category = emission.category_name
    return f"""{_mart_sql_header(emission)}
{emission.config_line()}

with f as (

    select * from {{{{ ref('fact_{category}_values') }}}}
    {{% if is_incremental() %}}
    where captured_at > (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{{{ this }}}}
    )
    {{% endif %}}

),

d as (

    select * from {{{{ ref('dim_{category}_values') }}}}

),

t as (

    select * from {{{{ ref('dim_timeframe_values') }}}}

)

select
{select_lines},
    f.fact_hash_id,
    f.captured_at
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
order by {emission.time_column}
"""


def mart_yml(emission: Emission) -> str:
    """Minimal properties for the uncontracted mart: name and description
    only, so the F-14 fixed-point delta list stays exhaustive (rule 5)."""
    category = emission.category_name
    doc = {
        "version": 2,
        "models": [
            {
                "name": f"mart_{category}_typed",
                "description": (
                    f"Materialized typed mart over the star for the"
                    f" {category} category: the typed projection's SELECT"
                    " as a table, lean shape, ordered by the time column;"
                    " one row per fact row, fact_hash_id kept as the"
                    " provenance pointer and captured_at as the incremental"
                    " watermark (D-38). Uncontracted by design (D-17 as"
                    " amended by D-36); derivative of the fact, dimension,"
                    " and timeframe payloads."
                ),
            }
        ],
    }
    body = yaml.dump(
        doc,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=2000,
        default_flow_style=False,
    )
    return _mart_yml_header(emission) + body


def projection_yml(emission: Emission) -> str:
    """Minimal properties for the uncontracted view: name and description
    only, so the F-14 fixed-point delta list stays exhaustive (rule 5)."""
    category = emission.category_name
    doc = {
        "version": 2,
        "models": [
            {
                "name": f"vw_{category}_typed",
                "description": (
                    f"Typed projection over the star for the {category}"
                    " category: json_extract plus cast per manifest field,"
                    " one row per fact row. Uncontracted by design (D-17);"
                    " derivative of the fact, dimension, and timeframe"
                    " payloads."
                ),
            }
        ],
    }
    body = yaml.dump(
        doc,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=2000,
        default_flow_style=False,
    )
    return _projection_yml_header(emission) + body


def _data_test(model: str, column: str, kind: str, contract_version: str) -> dict:
    if kind == "not_null":
        check, phrase = "field_required", "no missing values"
    else:
        check, phrase = "field_unique", "no duplicate values"
    return {
        kind: {
            "config": {
                "severity": "warn",
                "meta": {
                    "datacontract_cli": {
                        "check": f"{model}__{column}__{check}",
                        "include_in_tests": True,
                        "contract_versions": [contract_version],
                        "generated": True,
                    }
                },
            },
            "description": f"Check that field {column} has {phrase}",
        }
    }


def properties_yml(emission: Emission, model_name: str) -> str:
    """One properties file at the sync fixed point (spec §6; F-17, F-18)."""
    star_object = next(
        obj
        for obj in emission.star["schema"]
        if obj["name"] == model_name
    )
    contract_version = emission.star["version"]
    pk_columns = [
        prop["name"]
        for prop in star_object["properties"]
        if prop.get("primaryKey")
    ]
    single_pk = pk_columns[0] if len(pk_columns) == 1 else None

    columns = []
    for prop in star_object["properties"]:
        column: dict = {"name": prop["name"], "data_type": prop["physicalType"]}
        if prop.get("required"):
            column["constraints"] = [{"type": "not_null"}]
        column["description"] = _description(prop["description"])
        tests = []
        if prop.get("required"):
            tests.append(
                _data_test(model_name, prop["name"], "not_null", contract_version)
            )
        if prop["name"] == single_pk:
            tests.append(
                _data_test(model_name, prop["name"], "unique", contract_version)
            )
        if tests:
            column["data_tests"] = tests
        columns.append(column)

    doc = {
        "version": 2,
        "models": [
            {
                "name": model_name,
                "description": _description(star_object["description"]),
                "config": {
                    "contract": {"enforced": True},
                    "meta": {
                        "datacontract_cli": {"contract_id": emission.star["id"]}
                    },
                },
                "columns": columns,
            }
        ],
    }
    body = yaml.dump(
        doc,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=2000,
        default_flow_style=False,
    )
    return emission.yml_header() + body


def emit_models(emission: Emission) -> dict[str, str]:
    """The Sitting I emission set: nine models plus nine properties files."""
    category = emission.category_name
    models = {
        f"dim_{category}_values.sql": category_values_sql(emission),
        f"dim_{category}_columns.sql": category_columns_sql(emission),
        "dim_source_values.sql": source_values_sql(emission),
        "dim_source_columns.sql": source_columns_sql(emission),
        "dim_run_values.sql": run_values_sql(emission),
        "dim_run_columns.sql": run_columns_sql(emission),
        "dim_timeframe_values.sql": timeframe_values_sql(emission),
        "dim_timeframe_columns.sql": timeframe_columns_sql(emission),
        f"fact_{category}_values.sql": fact_values_sql(emission),
    }
    for sql_name in list(models):
        model_name = sql_name.removesuffix(".sql")
        models[f"{model_name}.yml"] = properties_yml(emission, model_name)
    return models


def emit_extended_models(
    emission: Emission, compiled: dict, marts: str = "both"
) -> dict[str, str]:
    """The extended-star additions (spec §5): the registry, carried from
    the compiled-context artifact, plus the typed surface per the
    engine.marts configuration (D-36): the materialized mart under
    ``table`` or ``both``, the projection view under ``view`` or ``both``.
    Registry properties ride the existing fixed-point emitter; the
    amended gold contract's context_registry object drives them."""
    category = emission.category_name
    files = {
        "context_registry.sql": registry_sql(emission, compiled),
        "context_registry.yml": properties_yml(emission, "context_registry"),
    }
    if marts in ("view", "both"):
        files[f"vw_{category}_typed.sql"] = projection_sql(emission)
        files[f"vw_{category}_typed.yml"] = projection_yml(emission)
    if marts in ("table", "both"):
        files[f"mart_{category}_typed.sql"] = mart_sql(emission)
        files[f"mart_{category}_typed.yml"] = mart_yml(emission)
    return files
