"""Model and properties emission at the sync fixed point (spec §5, §6).

Every emitted byte is deterministic from the two contracts plus
ENGINE_VERSION. SQL: payloads are ``lower(to_json(struct_pack(...)))``
with fields pre-sorted by lowercased name (sortedness is an emission-time
property, F-11), every value cast to VARCHAR, record keys ``sha256()``
computed in SQL uniformly — constant source and run payloads included.
Schema keys are Python literals via ``metricmine.keys.manifest_key``.
Properties YAML is emitted in sync's own canonical form (F-18) so gate 3
has nothing to rewrite (Q8/F-14): ``yaml.safe_dump`` with descriptions
parsed from folded ``>`` contract scalars forced single-quoted, the
sync-shaped ``not_null`` block per required column, and the ``unique:``
twin per single-column primaryKey (F-17; composite keys get none).
"""

from __future__ import annotations

import yaml

from metricmine.engine import ENGINE_VERSION
from metricmine.keys import canonical_manifest, manifest_key

_SQL_HEADER = (
    "-- Generated by metricmine-engine v{engine} from {mapping_id}"
    " v{mapping_version} + {gold_id} v{gold_version}.\n"
    "-- Engine-owned (D-09): do not edit; flag drift instead (rule 8)."
    " Spec: docs/spec/engine.md.\n"
)
_YML_HEADER = (
    "# Generated by metricmine-engine v{engine} from {mapping_id}"
    " v{mapping_version} + {gold_id} v{gold_version}.\n"
    "# Engine-owned (D-09): do not edit; flag drift instead (rule 8)."
    " Spec: docs/spec/engine.md.\n"
)


class _FoldedStr(str):
    """A description parsed from a folded ``>`` contract scalar.

    Sync re-emits such descriptions single-quoted with the trailing
    newline stripped (F-18); forcing the style here keeps the emitted
    bytes at the fixed point.
    """


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(
    _FoldedStr,
    lambda dumper, value: dumper.represent_scalar(
        "tag:yaml.org,2002:str", str(value), style="'"
    ),
)


def _description(raw: str) -> str:
    if raw.endswith("\n"):
        return _FoldedStr(raw.rstrip("\n"))
    return raw


class Emission:
    """Parameter view over the validated contracts."""

    def __init__(self, mapping: dict, star: dict) -> None:
        self.mapping = mapping
        self.star = star
        self.category = mapping["schema"][0]
        self.category_name = self.category["name"]
        self.source_table = self.category["sourceTable"]
        self.source_model = self.source_table.split(".", 1)[1]
        self.time_column = self.category["timeColumn"]
        self.time_grain = self.category["timeGrain"]
        self.header_args = {
            "engine": ENGINE_VERSION,
            "mapping_id": mapping["id"],
            "mapping_version": mapping["version"],
            "gold_id": star["id"],
            "gold_version": star["version"],
        }

        properties = self.category["properties"]
        self.dimension_fields = [
            p["name"] for p in properties if p["mappingRole"] == "dimension"
        ]
        self.measure_fields = [
            p["name"] for p in properties if p["mappingRole"] == "measure"
        ]
        self.derived_identifiers = [
            entry
            for entry in self.category["grain"].get("degenerateIdentifiers", [])
            if entry["source"] == "derived"
        ]
        carried = [
            entry["column"]
            for entry in self.category["grain"].get("degenerateIdentifiers", [])
            if entry["source"] == "column"
        ]
        self.dim_payload_columns = self.dimension_fields + [
            column for column in carried if column not in self.dimension_fields
        ]

        # Declared manifest orders (spec §3): dimension-role fields in
        # contract order with derived identifiers last; measures in
        # contract order; the star-global manifests are fixed.
        self.dim_manifest = self.dim_payload_columns + [
            entry["name"] for entry in self.derived_identifiers
        ]
        self.measure_manifest = list(self.measure_fields)
        self.source_manifest = ["source_table"]
        self.run_manifest = [
            "mapping_contract_name",
            "mapping_contract_version",
            "engine_version",
        ]
        self.timeframe_manifest = [self.time_column]

        self.dim_col_key = manifest_key(self.dim_manifest)
        self.fact_col_key = manifest_key(self.measure_manifest)
        self.source_col_key = manifest_key(self.source_manifest)
        self.run_col_key = manifest_key(self.run_manifest)
        self.timeframe_col_key = manifest_key(self.timeframe_manifest)

        self.run_entries = {
            "mapping_contract_name": f"'{mapping['id']}'",
            "mapping_contract_version": f"'{mapping['version']}'",
            "engine_version": f"'{ENGINE_VERSION}'",
        }

    def sql_header(self) -> str:
        return _SQL_HEADER.format(**self.header_args)

    def yml_header(self) -> str:
        return _YML_HEADER.format(**self.header_args)


def _struct_block(entries: dict[str, str], indent: int) -> str:
    """Render struct_pack member lines, fields sorted by lowercased name.

    ``entries`` maps field name to its SQL value expression; a multi-line
    expression (the nested derived-identifier payload) is indented four
    deeper than its member line by construction.
    """
    pad = " " * indent
    lines = [
        f"{pad}{name} := {expression}"
        for name, expression in sorted(
            entries.items(), key=lambda item: item[0].lower()
        )
    ]
    return ",\n".join(lines)


def _cast_entries(columns: list[str]) -> dict[str, str]:
    return {column: f"cast({column} as varchar)" for column in columns}


def _derived_expression(of_columns: list[str], indent: int) -> str:
    """The nested canonical payload of a derived degenerate identifier."""
    inner = _struct_block(_cast_entries(of_columns), indent + 4)
    pad = " " * indent
    return f"sha256(lower(to_json(struct_pack(\n{inner}\n{pad}))))"


def _dim_payload_entries(emission: Emission, indent: int) -> dict[str, str]:
    entries = _cast_entries(emission.dim_payload_columns)
    for identifier in emission.derived_identifiers:
        entries[identifier["name"]] = _derived_expression(
            identifier["of"], indent
        )
    return entries


def _timeframe_expression(emission: Emission) -> str:
    return (
        f"cast(date_trunc('{emission.time_grain}',"
        f" {emission.time_column}) as varchar)"
    )


def category_values_sql(emission: Emission) -> str:
    entries = _struct_block(_dim_payload_entries(emission, 12), 12)
    return f"""{emission.sql_header()}
with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}

),

payloads as (

    select distinct lower(to_json(struct_pack(
{entries}
        ))) as dim_values
    from source

)

select
    sha256(dim_values)          as dim_hash_id,
    '{emission.dim_col_key}' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at
from payloads
"""


def category_columns_sql(emission: Emission) -> str:
    dim_manifest = canonical_manifest(emission.dim_manifest)
    measure_manifest = canonical_manifest(emission.measure_manifest)
    return f"""{emission.sql_header()}
with manifests as (

    select '{dim_manifest}' as dim_columns, '{emission.dim_col_key}' as dim_col_hash_id
    union all
    select '{measure_manifest}', '{emission.fact_col_key}'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
"""


def source_values_sql(emission: Emission) -> str:
    return f"""{emission.sql_header()}
with payload as (

    select lower(to_json(struct_pack(
            source_table := '{emission.source_table}'
        ))) as source_values

)

select
    sha256(source_values)      as source_hash_id,
    '{emission.source_col_key}' as source_col_hash_id,
    source_values,
    current_localtimestamp()    as loaded_at
from payload
"""


def run_values_sql(emission: Emission) -> str:
    entries = _struct_block(emission.run_entries, 12)
    return f"""{emission.sql_header()}
with payload as (

    select lower(to_json(struct_pack(
{entries}
        ))) as run_values

)

select
    sha256(run_values)      as run_hash_id,
    '{emission.run_col_key}' as run_col_hash_id,
    run_values,
    current_localtimestamp()    as loaded_at
from payload
"""


def timeframe_values_sql(emission: Emission) -> str:
    entry = f"{emission.time_column} := {_timeframe_expression(emission)}"
    return f"""{emission.sql_header()}
with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}

),

payloads as (

    select distinct lower(to_json(struct_pack(
            {entry}
        ))) as timeframe_values
    from source

)

select
    sha256(timeframe_values)    as timeframe_hash_id,
    '{emission.timeframe_col_key}' as timeframe_col_hash_id,
    timeframe_values,
    current_localtimestamp()    as loaded_at
from payloads
"""


def _shared_columns_sql(
    emission: Emission, prefix: str, key: str, manifest: list[str]
) -> str:
    return f"""{emission.sql_header()}
select
    '{key}' as {prefix}_col_hash_id,
    '{canonical_manifest(manifest)}' as {prefix}_columns,
    current_localtimestamp()    as loaded_at
"""


def source_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission, "source", emission.source_col_key, emission.source_manifest
    )


def run_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission, "run", emission.run_col_key, emission.run_manifest
    )


def timeframe_columns_sql(emission: Emission) -> str:
    return _shared_columns_sql(
        emission,
        "timeframe",
        emission.timeframe_col_key,
        emission.timeframe_manifest,
    )


def fact_values_sql(emission: Emission) -> str:
    measure_entries = _struct_block(_cast_entries(emission.measure_fields), 12)
    dim_entries = _struct_block(_dim_payload_entries(emission, 12), 12)
    timeframe_entry = (
        f"{emission.time_column} := {_timeframe_expression(emission)}"
    )
    source_entry = f"source_table := '{emission.source_table}'"
    run_entries = _struct_block(emission.run_entries, 12)
    return f"""{emission.sql_header()}
with source as (

    select * from {{{{ ref('{emission.source_model}') }}}}

),

keyed as (

    select
        lower(to_json(struct_pack(
{measure_entries}
        ))) as fact_values,
        lower(to_json(struct_pack(
{dim_entries}
        ))) as dim_payload,
        lower(to_json(struct_pack(
            {timeframe_entry}
        ))) as timeframe_payload
    from source

)

select
    sha256(fact_values)         as fact_hash_id,
    sha256(lower(to_json(struct_pack(
            {source_entry}
        )))) as source_hash_id,
    sha256(timeframe_payload)   as timeframe_hash_id,
    sha256(dim_payload)         as dim_hash_id,
    sha256(lower(to_json(struct_pack(
{run_entries}
        )))) as run_hash_id,
    '{emission.fact_col_key}' as fact_col_hash_id,
    fact_values,
    current_localtimestamp()    as loaded_at
from keyed
"""


def _data_test(model: str, column: str, kind: str, contract_version: str) -> dict:
    if kind == "not_null":
        check, phrase = "field_required", "no missing values"
    else:
        check, phrase = "field_unique", "no duplicate values"
    return {
        kind: {
            "config": {
                "severity": "warn",
                "meta": {
                    "datacontract_cli": {
                        "check": f"{model}__{column}__{check}",
                        "include_in_tests": True,
                        "contract_versions": [contract_version],
                        "generated": True,
                    }
                },
            },
            "description": f"Check that field {column} has {phrase}",
        }
    }


def properties_yml(emission: Emission, model_name: str) -> str:
    """One properties file at the sync fixed point (spec §6; F-17, F-18)."""
    star_object = next(
        obj
        for obj in emission.star["schema"]
        if obj["name"] == model_name
    )
    contract_version = emission.star["version"]
    pk_columns = [
        prop["name"]
        for prop in star_object["properties"]
        if prop.get("primaryKey")
    ]
    single_pk = pk_columns[0] if len(pk_columns) == 1 else None

    columns = []
    for prop in star_object["properties"]:
        column: dict = {"name": prop["name"], "data_type": prop["physicalType"]}
        if prop.get("required"):
            column["constraints"] = [{"type": "not_null"}]
        column["description"] = _description(prop["description"])
        tests = []
        if prop.get("required"):
            tests.append(
                _data_test(model_name, prop["name"], "not_null", contract_version)
            )
        if prop["name"] == single_pk:
            tests.append(
                _data_test(model_name, prop["name"], "unique", contract_version)
            )
        if tests:
            column["data_tests"] = tests
        columns.append(column)

    doc = {
        "version": 2,
        "models": [
            {
                "name": model_name,
                "description": _description(star_object["description"]),
                "config": {
                    "contract": {"enforced": True},
                    "meta": {
                        "datacontract_cli": {"contract_id": emission.star["id"]}
                    },
                },
                "columns": columns,
            }
        ],
    }
    body = yaml.dump(
        doc,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=2000,
        default_flow_style=False,
    )
    return emission.yml_header() + body


def emit_models(emission: Emission) -> dict[str, str]:
    """The Sitting I emission set: nine models plus nine properties files."""
    category = emission.category_name
    models = {
        f"dim_{category}_values.sql": category_values_sql(emission),
        f"dim_{category}_columns.sql": category_columns_sql(emission),
        "dim_source_values.sql": source_values_sql(emission),
        "dim_source_columns.sql": source_columns_sql(emission),
        "dim_run_values.sql": run_values_sql(emission),
        "dim_run_columns.sql": run_columns_sql(emission),
        "dim_timeframe_values.sql": timeframe_values_sql(emission),
        "dim_timeframe_columns.sql": timeframe_columns_sql(emission),
        f"fact_{category}_values.sql": fact_values_sql(emission),
    }
    for sql_name in list(models):
        model_name = sql_name.removesuffix(".sql")
        models[f"{model_name}.yml"] = properties_yml(emission, model_name)
    return models
