-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_planes@1.0.0 (model: silver_nyc_planes)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_planes__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_planes", "description": "Grain enforcement: no duplicate (tail_number) combinations. Declared at error severity because the primaryKey-flag composite test generates at warn severity at datacontract-cli 1.0.12 (rule 5: uniqueness as a test, never a trusted constraint)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT tail_number
  FROM silver.silver_nyc_planes
  GROUP BY tail_number
  HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
