-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_airlines@1.0.0 (model: silver_nyc_airlines)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_airlines__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_airlines", "description": "Grain enforcement: no duplicate (carrier_code) combinations. Declared at error severity because the primaryKey-flag composite test generates at warn severity at datacontract-cli 1.0.12 (rule 5: uniqueness as a test, never a trusted constraint)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT carrier_code
  FROM silver.silver_nyc_airlines
  GROUP BY carrier_code
  HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
