-- Generated by metricmine-engine v0.5.0 from gold_unified_event_star v1.5.0 over 1 mapping contract (gold_invoice_lines_mapping v1.1.1).
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with rows as (

    select * from (values
        ('61e74223d961799a0f8b12bf9045b422b5cad4fc9273e1ce3f65eb07966a2e1f', 'source', 'gold_unified_event_star', '1.5.0', '{"manifest":["source_table"],"role":"source","source_tables":["silver.silver_invoice_lines"]}'),
        ('dacafb1855b6ce1628eb3be9b6c8eeeedc3d4f45454a6fd87093deda9d0cc848', 'run', 'gold_unified_event_star', '1.5.0', '{"manifest":["mapping_contract_name","mapping_contract_version","engine_version"],"role":"run"}'),
        ('882bb5e70283711a0c90460b64b632f83786eaf265e1e044bfbe288e6144ae98', 'timeframe', 'gold_unified_event_star', '1.5.0', '{"categories":{"invoice_lines":{"field":{"description":"Invoice timestamp; the declared time column.","logicalType":"date","mappingRole":"time","physicalType":"TIMESTAMP"},"time_column":"invoiced_at","time_grain":"minute"}},"fields":{"grain":{"description":"The declared time grain of the category the period belongs to (minute, hour, day, week, month, quarter, year).","logicalType":"string","physicalType":"VARCHAR"},"period_start":{"description":"The category''s declared time column truncated to its grain and rendered canonically; equal periods at equal grain hash to one row whichever category minted them (the conformed calendar, D-17 Amendment R).","logicalType":"date","physicalType":"TIMESTAMP"}},"manifest":["grain","period_start"],"role":"timeframe"}'),
        ('2d27bd360b5092ff22047c65407ff05699afad98f455de2409665a5950a05e82', 'invoice_lines', 'gold_invoice_lines_mapping', '1.1.1', '{"category":"invoice_lines","conformed_keys":{},"derived_identifiers":{"line_identity":{"derivation":"canonical-key-v2","of":["invoice_id","stock_code","quantity","unit_price"],"source":"derived"}},"fields":{"country":{"description":"Customer country as landed; the signature-test dimension, mapped at v1.1.0.","logicalType":"string","mappingRole":"dimension","physicalType":"VARCHAR"},"customer_id":{"description":"Customer identifier; null on guest checkouts.","logicalType":"integer","mappingRole":"dimension","physicalType":"INTEGER"},"invoice_id":{"description":"Invoice number; C prefix marks a cancellation.","logicalType":"string","mappingRole":"dimension","physicalType":"VARCHAR"},"is_cancellation":{"description":"Cancellation flag; exclusion is a consumer decision.","logicalType":"boolean","mappingRole":"dimension","physicalType":"BOOLEAN"},"product_description":{"description":"Product description; nulls retained.","logicalType":"string","mappingRole":"dimension","physicalType":"VARCHAR"},"stock_code":{"description":"Product code as landed.","logicalType":"string","mappingRole":"dimension","physicalType":"VARCHAR"}},"manifest":["invoice_id","is_cancellation","stock_code","product_description","customer_id","country","line_identity"],"role":"dimensions","source_table":"silver.silver_invoice_lines","time_column":"invoiced_at","time_grain":"minute","typed_surface":"mart_invoice_lines_typed"}'),
        ('9dbc23cabca765eeaed72eb8161c90b5ae7857f81031656002f03e5bd9d99319', 'invoice_lines', 'gold_invoice_lines_mapping', '1.1.1', '{"category":"invoice_lines","fields":{"quantity":{"description":"Units on the line; negative only on cancellations.","logicalType":"integer","mappingRole":"measure","physicalType":"INTEGER"},"unit_price":{"description":"Unit price in sterling; zero-price lines retained.","logicalType":"number","mappingRole":"measure","physicalType":"DECIMAL(10,2)"}},"manifest":["quantity","unit_price"],"role":"measures","source_table":"silver.silver_invoice_lines","typed_surface":"mart_invoice_lines_typed"}')
    ) as t (schema_key, entity_group, contract_name, contract_version, compiled_context)

)

select
    schema_key,
    entity_group,
    contract_name,
    contract_version,
    compiled_context,
    current_localtimestamp()    as loaded_at
from rows
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.schema_key = rows.schema_key
)
{% endif %}
