-- Generated by metricmine-engine v0.5.0 from gold_airport_weather_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_airport_weather') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

payloads as (

    select
        lower(to_json(struct_pack(
            airport_code := cast(airport_code as varchar),
            airport_elevation_ft := cast(airport_elevation_ft as varchar),
            airport_longest_runway_ft := cast(airport_longest_runway_ft as varchar),
            airport_municipality := cast(airport_municipality as varchar),
            airport_name := cast(airport_name as varchar),
            observation_identity := sha256(lower(to_json(struct_pack(
                airport_code := cast(airport_code as varchar),
                observed_hour_utc := cast(observed_hour_utc as varchar)
            )))),
            observed_date_local := cast(observed_date_local as varchar),
            observed_hour_local := cast(observed_hour_local as varchar)
        ))) as dim_values,
        captured_at
    from source

),

grouped as (

    select
        dim_values,
        min(captured_at) as captured_at
    from payloads
    group by dim_values

)

select
    sha256(dim_values)          as dim_hash_id,
    'bd757e61f7e3a9e49d069ca74dc21ad28e2c598d588d486bf4cda0d088385161' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.dim_hash_id = sha256(grouped.dim_values)
)
{% endif %}
