-- Generated by metricmine-engine v0.2.0 from gold_invoice_lines_mapping v1.1.0 + gold_unified_event_star v1.2.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with payload as (

    select lower(to_json(struct_pack(
            engine_version := '0.2.0',
            mapping_contract_name := 'gold_invoice_lines_mapping',
            mapping_contract_version := '1.1.0'
        ))) as run_values

)

select
    sha256(run_values)      as run_hash_id,
    'dacafb1855b6ce1628eb3be9b6c8eeeedc3d4f45454a6fd87093deda9d0cc848' as run_col_hash_id,
    run_values,
    current_localtimestamp()    as loaded_at
from payload
