-- Generated by metricmine-engine v0.5.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.5.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_invoice_lines') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

payloads as (

    select
        lower(to_json(struct_pack(
            country := cast(country as varchar),
            customer_id := cast(customer_id as varchar),
            invoice_id := cast(invoice_id as varchar),
            is_cancellation := cast(is_cancellation as varchar),
            line_identity := sha256(lower(to_json(struct_pack(
                invoice_id := cast(invoice_id as varchar),
                quantity := cast(quantity as varchar),
                stock_code := cast(stock_code as varchar),
                unit_price := cast(unit_price as varchar)
            )))),
            product_description := cast(product_description as varchar),
            stock_code := cast(stock_code as varchar)
        ))) as dim_values,
        captured_at
    from source

),

grouped as (

    select
        dim_values,
        min(captured_at) as captured_at
    from payloads
    group by dim_values

)

select
    sha256(dim_values)          as dim_hash_id,
    '2d27bd360b5092ff22047c65407ff05699afad98f455de2409665a5950a05e82' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.dim_hash_id = sha256(grouped.dim_values)
)
{% endif %}
