-- Generated by metricmine-engine v0.5.0 from gold_unified_event_star v1.6.0 over 3 mapping contracts (gold_airport_weather_mapping v1.0.0, gold_flights_mapping v1.0.0, gold_invoice_lines_mapping v1.1.1).
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source_airport_weather as (

    select * from {{ ref('silver_airport_weather') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

source_flights as (

    select * from {{ ref('silver_flights') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

source_invoice_lines as (

    select * from {{ ref('silver_invoice_lines') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

payloads as (

    select
        lower(to_json(struct_pack(
            grain := 'hour',
            period_start := cast(date_trunc('hour', observed_hour_utc) as varchar)
        ))) as timeframe_values,
        captured_at
    from source_airport_weather
    union all
    select
        lower(to_json(struct_pack(
            grain := 'hour',
            period_start := cast(date_trunc('hour', departure_hour_utc) as varchar)
        ))) as timeframe_values,
        captured_at
    from source_flights
    union all
    select
        lower(to_json(struct_pack(
            grain := 'minute',
            period_start := cast(date_trunc('minute', invoiced_at) as varchar)
        ))) as timeframe_values,
        captured_at
    from source_invoice_lines

),

grouped as (

    select
        timeframe_values,
        min(captured_at) as captured_at
    from payloads
    group by timeframe_values

)

select
    sha256(timeframe_values)    as timeframe_hash_id,
    '882bb5e70283711a0c90460b64b632f83786eaf265e1e044bfbe288e6144ae98' as timeframe_col_hash_id,
    timeframe_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.timeframe_hash_id = sha256(grouped.timeframe_values)
)
{% endif %}
