-- Generated by metricmine-engine v0.3.0 from gold_invoice_lines_mapping v1.1.0 + gold_unified_event_star v1.2.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with source as (

    select * from {{ ref('silver_invoice_lines') }}

),

payloads as (

    select distinct lower(to_json(struct_pack(
            invoiced_at := cast(date_trunc('minute', invoiced_at) as varchar)
        ))) as timeframe_values
    from source

)

select
    sha256(timeframe_values)    as timeframe_hash_id,
    '8f99de0c5aa34c2e3e2e66890f7b986f0c2d39b9276b901f1232efd0ebcc0dd8' as timeframe_col_hash_id,
    timeframe_values,
    current_localtimestamp()    as loaded_at
from payloads
