-- Generated by metricmine-engine v0.5.0 from gold_airport_weather_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with manifests as (

    select '["airport_code","observed_date_local","observed_hour_local","airport_name","airport_municipality","airport_elevation_ft","airport_longest_runway_ft","observation_identity"]' as dim_columns, 'bd757e61f7e3a9e49d069ca74dc21ad28e2c598d588d486bf4cda0d088385161' as dim_col_hash_id
    union all
    select '["temp_f","dewpoint_f","humidity_pct","wind_dir_degrees","wind_speed_mph","wind_gust_mph","precip_inches","pressure_mb","visibility_miles"]', '504053d805b31eaecbcfa7e015ebb22595650ece5997237ad14fa1a8aa15fe3d'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.dim_col_hash_id = manifests.dim_col_hash_id
)
{% endif %}
