-- Generated by metricmine-engine v0.1.0 from gold_invoice_lines_mapping v1.0.0 + gold_unified_event_star v1.1.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

select
    '61e74223d961799a0f8b12bf9045b422b5cad4fc9273e1ce3f65eb07966a2e1f' as source_col_hash_id,
    '["source_table"]' as source_columns,
    current_localtimestamp()    as loaded_at
