-- Generated by metricmine-engine v0.5.0 from gold_airport_weather_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_airport_weather') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

keyed as (

    select
        lower(to_json(struct_pack(
            dewpoint_f := cast(dewpoint_f as varchar),
            humidity_pct := cast(humidity_pct as varchar),
            precip_inches := cast(precip_inches as varchar),
            pressure_mb := cast(pressure_mb as varchar),
            temp_f := cast(temp_f as varchar),
            visibility_miles := cast(visibility_miles as varchar),
            wind_dir_degrees := cast(wind_dir_degrees as varchar),
            wind_gust_mph := cast(wind_gust_mph as varchar),
            wind_speed_mph := cast(wind_speed_mph as varchar)
        ))) as fact_values,
        lower(to_json(struct_pack(
            airport_code := cast(airport_code as varchar),
            airport_elevation_ft := cast(airport_elevation_ft as varchar),
            airport_longest_runway_ft := cast(airport_longest_runway_ft as varchar),
            airport_municipality := cast(airport_municipality as varchar),
            airport_name := cast(airport_name as varchar),
            observation_identity := sha256(lower(to_json(struct_pack(
                airport_code := cast(airport_code as varchar),
                observed_hour_utc := cast(observed_hour_utc as varchar)
            )))),
            observed_date_local := cast(observed_date_local as varchar),
            observed_hour_local := cast(observed_hour_local as varchar)
        ))) as dim_payload,
        lower(to_json(struct_pack(
            grain := 'hour',
            period_start := cast(date_trunc('hour', observed_hour_utc) as varchar)
        ))) as timeframe_payload,
        captured_at
    from source

),

hashed as (

    select
        sha256(fact_values)         as fact_hash_id,
        sha256(lower(to_json(struct_pack(
                source_table := 'silver.silver_airport_weather'
            )))) as source_hash_id,
        sha256(timeframe_payload)   as timeframe_hash_id,
        sha256(dim_payload)         as dim_hash_id,
        sha256(lower(to_json(struct_pack(
                engine_version := '0.5.0',
                mapping_contract_name := 'gold_airport_weather_mapping',
                mapping_contract_version := '1.0.0'
            )))) as run_hash_id,
        '504053d805b31eaecbcfa7e015ebb22595650ece5997237ad14fa1a8aa15fe3d' as fact_col_hash_id,
        fact_values,
        captured_at
    from keyed

)

select
    fact_hash_id,
    source_hash_id,
    timeframe_hash_id,
    dim_hash_id,
    run_hash_id,
    fact_col_hash_id,
    fact_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from hashed
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.fact_hash_id = hashed.fact_hash_id
      and t.source_hash_id = hashed.source_hash_id
      and t.timeframe_hash_id = hashed.timeframe_hash_id
      and t.dim_hash_id = hashed.dim_hash_id
)
{% endif %}
