-- Generated by metricmine-engine v0.4.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.4.0.
-- Derivative typed mart over the star; uncontracted by design (D-17 as amended by D-36). Do not edit; flag drift instead (rule 8).

{{ config(materialized='table') }}

with f as (

    select * from {{ ref('fact_invoice_lines_values') }}
    {% if is_incremental() %}
    where captured_at > (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

d as (

    select * from {{ ref('dim_invoice_lines_values') }}

),

t as (

    select * from {{ ref('dim_timeframe_values') }}

)

select
    cast(json_extract_string(d.dim_values, '$.invoice_id') as VARCHAR) as invoice_id,
    cast(json_extract_string(d.dim_values, '$.is_cancellation') as BOOLEAN) as is_cancellation,
    cast(json_extract_string(d.dim_values, '$.stock_code') as VARCHAR) as stock_code,
    cast(json_extract_string(d.dim_values, '$.product_description') as VARCHAR) as product_description,
    cast(json_extract_string(d.dim_values, '$.customer_id') as INTEGER) as customer_id,
    cast(json_extract_string(d.dim_values, '$.country') as VARCHAR) as country,
    cast(json_extract_string(t.timeframe_values, '$.invoiced_at') as TIMESTAMP) as invoiced_at,
    cast(json_extract_string(f.fact_values, '$.quantity') as INTEGER) as quantity,
    cast(json_extract_string(f.fact_values, '$.unit_price') as DECIMAL(10,2)) as unit_price,
    f.fact_hash_id,
    f.captured_at
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
order by invoiced_at
