-- Generated by metricmine-engine v0.5.0 from gold_airport_weather_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Derivative typed mart over the star; uncontracted by design (D-17 as amended by D-36). Do not edit; flag drift instead (rule 8).

{{ config(materialized='table') }}

with f as (

    select * from {{ ref('fact_airport_weather_values') }}
    {% if is_incremental() %}
    where captured_at > (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

d as (

    select * from {{ ref('dim_airport_weather_values') }}

),

t as (

    select * from {{ ref('dim_timeframe_values') }}

)

select
    cast(json_extract_string(d.dim_values, '$.airport_code') as VARCHAR) as airport_code,
    cast(json_extract_string(d.dim_values, '$.observed_date_local') as DATE) as observed_date_local,
    cast(json_extract_string(d.dim_values, '$.observed_hour_local') as INTEGER) as observed_hour_local,
    cast(json_extract_string(d.dim_values, '$.airport_name') as VARCHAR) as airport_name,
    cast(json_extract_string(d.dim_values, '$.airport_municipality') as VARCHAR) as airport_municipality,
    cast(json_extract_string(d.dim_values, '$.airport_elevation_ft') as INTEGER) as airport_elevation_ft,
    cast(json_extract_string(d.dim_values, '$.airport_longest_runway_ft') as INTEGER) as airport_longest_runway_ft,
    cast(json_extract_string(t.timeframe_values, '$.period_start') as TIMESTAMP) as observed_hour_utc,
    cast(json_extract_string(f.fact_values, '$.temp_f') as DOUBLE) as temp_f,
    cast(json_extract_string(f.fact_values, '$.dewpoint_f') as DOUBLE) as dewpoint_f,
    cast(json_extract_string(f.fact_values, '$.humidity_pct') as DOUBLE) as humidity_pct,
    cast(json_extract_string(f.fact_values, '$.wind_dir_degrees') as INTEGER) as wind_dir_degrees,
    cast(json_extract_string(f.fact_values, '$.wind_speed_mph') as DOUBLE) as wind_speed_mph,
    cast(json_extract_string(f.fact_values, '$.wind_gust_mph') as DOUBLE) as wind_gust_mph,
    cast(json_extract_string(f.fact_values, '$.precip_inches') as DOUBLE) as precip_inches,
    cast(json_extract_string(f.fact_values, '$.pressure_mb') as DOUBLE) as pressure_mb,
    cast(json_extract_string(f.fact_values, '$.visibility_miles') as DOUBLE) as visibility_miles,
    f.fact_hash_id,
    f.captured_at
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
order by observed_hour_utc
