-- Generated by metricmine-engine v0.5.0 from gold_flights_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Derivative typed mart over the star; uncontracted by design (D-17 as amended by D-36). Do not edit; flag drift instead (rule 8).

{{ config(materialized='table') }}

with f as (

    select * from {{ ref('fact_flights_values') }}
    {% if is_incremental() %}
    where captured_at > (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

d as (

    select * from {{ ref('dim_flights_values') }}

),

t as (

    select * from {{ ref('dim_timeframe_values') }}

)

select
    cast(json_extract_string(d.dim_values, '$.flight_date') as DATE) as flight_date,
    cast(json_extract_string(d.dim_values, '$.carrier_code') as VARCHAR) as carrier_code,
    cast(json_extract_string(d.dim_values, '$.flight_number') as INTEGER) as flight_number,
    cast(json_extract_string(d.dim_values, '$.origin_airport') as VARCHAR) as origin_airport,
    cast(json_extract_string(d.dim_values, '$.sched_dep_hhmm') as INTEGER) as sched_dep_hhmm,
    cast(json_extract_string(d.dim_values, '$.dest_airport') as VARCHAR) as dest_airport,
    cast(json_extract_string(d.dim_values, '$.tail_number') as VARCHAR) as tail_number,
    cast(json_extract_string(d.dim_values, '$.is_cancelled') as BOOLEAN) as is_cancelled,
    cast(json_extract_string(d.dim_values, '$.dep_hhmm') as INTEGER) as dep_hhmm,
    cast(json_extract_string(d.dim_values, '$.arr_hhmm') as INTEGER) as arr_hhmm,
    cast(json_extract_string(d.dim_values, '$.sched_arr_hhmm') as INTEGER) as sched_arr_hhmm,
    cast(json_extract_string(d.dim_values, '$.sched_dep_hour_local') as INTEGER) as sched_dep_hour_local,
    cast(json_extract_string(d.dim_values, '$.sched_dep_minute_local') as INTEGER) as sched_dep_minute_local,
    cast(json_extract_string(d.dim_values, '$.carrier_name') as VARCHAR) as carrier_name,
    cast(json_extract_string(d.dim_values, '$.aircraft_manufacturer') as VARCHAR) as aircraft_manufacturer,
    cast(json_extract_string(d.dim_values, '$.aircraft_model') as VARCHAR) as aircraft_model,
    cast(json_extract_string(d.dim_values, '$.aircraft_manufacture_year') as INTEGER) as aircraft_manufacture_year,
    cast(json_extract_string(d.dim_values, '$.aircraft_seat_count') as INTEGER) as aircraft_seat_count,
    cast(json_extract_string(d.dim_values, '$.aircraft_engine_type') as VARCHAR) as aircraft_engine_type,
    cast(json_extract_string(d.dim_values, '$.origin_airport_name') as VARCHAR) as origin_airport_name,
    cast(json_extract_string(d.dim_values, '$.origin_municipality') as VARCHAR) as origin_municipality,
    cast(json_extract_string(d.dim_values, '$.origin_elevation_ft') as INTEGER) as origin_elevation_ft,
    cast(json_extract_string(d.dim_values, '$.origin_longest_runway_ft') as INTEGER) as origin_longest_runway_ft,
    cast(json_extract_string(d.dim_values, '$.dest_airport_name') as VARCHAR) as dest_airport_name,
    cast(json_extract_string(d.dim_values, '$.dest_municipality') as VARCHAR) as dest_municipality,
    cast(json_extract_string(d.dim_values, '$.dest_iso_region') as VARCHAR) as dest_iso_region,
    cast(json_extract_string(d.dim_values, '$.dest_elevation_ft') as INTEGER) as dest_elevation_ft,
    cast(json_extract_string(d.dim_values, '$.dest_longest_runway_ft') as INTEGER) as dest_longest_runway_ft,
    cast(json_extract_string(t.timeframe_values, '$.period_start') as TIMESTAMP) as departure_hour_utc,
    cast(json_extract_string(f.fact_values, '$.dep_delay_minutes') as INTEGER) as dep_delay_minutes,
    cast(json_extract_string(f.fact_values, '$.arr_delay_minutes') as INTEGER) as arr_delay_minutes,
    cast(json_extract_string(f.fact_values, '$.air_time_minutes') as INTEGER) as air_time_minutes,
    cast(json_extract_string(f.fact_values, '$.distance_miles') as INTEGER) as distance_miles,
    f.fact_hash_id,
    f.captured_at
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
order by departure_hour_utc
