-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_airport_weather@1.0.0 (model: silver_airport_weather)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_airport_weather__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_airport_weather", "description": "Join completeness, airport: at least 1.00 of rows resolve airport_code in silver_ourairports_airports.iata_code (measured 1.0000 at profile v0001; the three NYC airports all resolve). The M2 floor of D-41, declared below the measured value so a reference refresh that adds coverage passes and one that loses it fails."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT 1 FROM {{ ref('silver_airport_weather') }}
  HAVING SUM(CASE WHEN airport_name IS NOT NULL THEN 1 ELSE 0 END) * 1.0 / COUNT(*) < 1.0
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
