"""Unit surface for the auto-modeling engine (docs/spec/engine.md §5; D-29).

CI-lane, keyless: everything here runs from the committed contracts and the
committed golden fixtures — no warehouse, no network. The fixtures under
``tests/golden/emitted/`` are the sync fixed point verified at the pre-I
rehearsal (sync pass over the emitted set updated 0 YAML files; second pass
byte-identical), so byte-equality against them IS the Q8 fixed-point claim
in test form, and emission determinism is meaningful because of it.

Interface under test (pinned at the Sitting I runbook):
- ``metricmine.engine.emit.build_emission_set(repo_root)`` — pure; returns
  ``{relative_path_under_transform/models/gold: content}`` for the nine
  models, nine properties files, and ``ownership-manifest.json``.
- ``metricmine.engine.reader`` — ``load_inputs(repo_root)``,
  ``validate_mapping(mapping, silver, json_schema)``, raising
  ``EngineContractError`` on any schema or cross-check violation.
"""

from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path

import pytest

from metricmine.engine.emit import build_emission_set
from metricmine.engine.reader import (
    EngineContractError,
    load_inputs,
    validate_mapping,
)

REPO = Path(__file__).resolve().parents[1]
FIXTURES = REPO / "tests" / "golden" / "emitted"

HEADER_SQL = "-- Generated by metricmine-engine v"
HEADER_YML = "# Generated by metricmine-engine v"


def _contract_version(contract_filename: str) -> str:
    import yaml

    doc = yaml.safe_load(
        (REPO / "contracts" / contract_filename).read_text(encoding="utf-8")
    )
    return doc["version"]


def test_emission_matches_golden_fixtures() -> None:
    """Same contracts in, byte-identical files out (D-29; Q8 fixed point)."""
    emitted = build_emission_set(REPO)
    fixture_names = sorted(p.name for p in FIXTURES.iterdir())
    assert sorted(emitted) == fixture_names
    for name, content in emitted.items():
        expected = (FIXTURES / name).read_text(encoding="utf-8")
        assert content == expected, f"{name} diverges from its golden fixture"


def test_emission_is_deterministic() -> None:
    """Two independent runs produce byte-identical sets."""
    first = build_emission_set(REPO)
    second = build_emission_set(REPO)
    assert first == second


def test_generated_by_headers_lead_every_file() -> None:
    """Engine-owned marker, exact form, first line of every emitted file
    (docs/spec/engine.md §5; D-09)."""
    emitted = build_emission_set(REPO)
    for name, content in emitted.items():
        if name.endswith(".sql"):
            assert content.startswith(HEADER_SQL), name
        elif name.endswith(".yml"):
            assert content.startswith(HEADER_YML), name
        else:
            assert name == "ownership-manifest.json"


def test_ownership_manifest_hashes_the_fixed_point() -> None:
    """The manifest covers every emitted file except itself, with sha256
    over the emitted bytes (docs/spec/engine.md §5)."""
    emitted = build_emission_set(REPO)
    manifest = json.loads(emitted["ownership-manifest.json"])
    listed = manifest["files"]
    expected_paths = {
        f"transform/models/gold/{name}"
        for name in emitted
        if name != "ownership-manifest.json"
    }
    assert set(listed) == expected_paths
    for path, digest in listed.items():
        content = emitted[path.rsplit("/", 1)[1]]
        actual = "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()
        assert digest == actual, f"{path} checksum mismatch"
    assert manifest["engine_version"]
    # Version assertions track the contracts dynamically so a contract
    # amendment refreshes the oracle without editing this test (F-19
    # lesson: literals here break on every legitimate version bump).
    assert manifest["sources"]["mapping_contract"]["version"] == _contract_version(
        "gold_invoice_lines_mapping.odcs.yaml"
    )
    assert manifest["sources"]["gold_contract"]["version"] == _contract_version(
        "gold_unified_event_star.odcs.yaml"
    )
    # The registry rides the compiled-context artifact (D-30): the manifest
    # pins the newest committed vNNNN, read dynamically like the contract
    # versions above.
    from metricmine.profiling.writer import latest_version

    newest = latest_version(REPO / "context" / "compiled")
    assert manifest["sources"]["compiled_context"]["version"] == f"v{newest:04d}"


def _inputs():
    return load_inputs(REPO)


def test_reader_accepts_the_committed_mapping_contract() -> None:
    inputs = _inputs()
    validate_mapping(inputs.mapping, inputs.silver, inputs.json_schema)


@pytest.mark.parametrize(
    "mutate, reason",
    [
        (
            lambda doc: doc["schema"][0].__setitem__("quality", []),
            "quality rules are dead letters in a mapping contract (F-12)",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__("name", "dim_invoice_lines"),
            "reserved category-name pattern (F-12 collision guard)",
        ),
        (
            lambda doc: doc["schema"][0]["grain"]["degenerateIdentifiers"][0][
                "of"
            ].append("no_such_column"),
            "derived-of references an undeclared field",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__("timeColumn", "quantity"),
            "timeColumn must carry mappingRole time",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__(
                "sourceTable", "silver.no_such_table"
            ),
            "sourceTable must name the silver contract's object",
        ),
    ],
)
def test_reader_rejects_invalid_mapping_contracts(mutate, reason) -> None:
    """Fail-closed static groundedness (docs/spec/engine.md §5)."""
    inputs = _inputs()
    broken = copy.deepcopy(inputs.mapping)
    mutate(broken)
    with pytest.raises(EngineContractError):
        validate_mapping(broken, inputs.silver, inputs.json_schema)


def test_marts_modes_shape_the_typed_surface() -> None:
    """engine.marts (D-36): `both` carries the mart and the view, `table`
    only the mart, `view` only the view; the registry pair rides every
    mode unchanged."""
    from metricmine.engine.emitters import Emission, emit_extended_models

    inputs = _inputs()
    emission = Emission(inputs.mapping, inputs.star)
    compiled = {"entries": []}
    both = set(emit_extended_models(emission, compiled, "both"))
    table = set(emit_extended_models(emission, compiled, "table"))
    view = set(emit_extended_models(emission, compiled, "view"))
    registry = {"context_registry.sql", "context_registry.yml"}
    mart = {"mart_invoice_lines_typed.sql", "mart_invoice_lines_typed.yml"}
    vw = {"vw_invoice_lines_typed.sql", "vw_invoice_lines_typed.yml"}
    assert both == registry | mart | vw
    assert table == registry | mart
    assert view == registry | vw


def test_unknown_marts_mode_fails_closed(monkeypatch) -> None:
    """An unrecognized engine.marts value refuses before anything emits
    (D-36), naming the key."""
    from metricmine.engine import emit as emit_module

    monkeypatch.setattr(
        emit_module,
        "_config",
        lambda repo_root: {
            "output_dir": "transform/models/gold",
            "marts": "sideways",
        },
    )
    with pytest.raises(EngineContractError, match="engine.marts"):
        emit_module.build_emission_set(REPO)


def test_mart_sql_is_lean_ordered_and_a_table() -> None:
    """The emitted mart (D-36): a materialized table, ordered by the time
    column, the business columns plus fact_hash_id, no derived identifier
    and no group hash key carried."""
    from metricmine.engine.emitters import Emission, mart_sql

    inputs = _inputs()
    sql = mart_sql(Emission(inputs.mapping, inputs.star))
    assert "materialized='table'" in sql
    assert sql.rstrip().endswith("order by invoiced_at")
    assert "    f.fact_hash_id\nfrom f" in sql
    assert "line_identity" not in sql
    # The group hash keys appear exactly twice each: the two sides of
    # their join condition, never as carried columns.
    assert sql.count("dim_hash_id") == 2
    assert sql.count("timeframe_hash_id") == 2
