"""Unit surface for the auto-modeling engine (docs/spec/engine.md §5; D-29).

CI-lane, keyless: everything here runs from the committed contracts and the
committed golden fixtures — no warehouse, no network. The fixtures under
``tests/golden/emitted/`` are the sync fixed point verified at the pre-I
rehearsal (sync pass over the emitted set updated 0 YAML files; second pass
byte-identical), so byte-equality against them IS the Q8 fixed-point claim
in test form, and emission determinism is meaningful because of it.

Interface under test (pinned at the Sitting I runbook):
- ``metricmine.engine.emit.build_emission_set(repo_root)`` — pure; returns
  ``{relative_path_under_transform/models/gold: content}`` for the nine
  models, nine properties files, and ``ownership-manifest.json``.
- ``metricmine.engine.reader`` — ``load_inputs(repo_root)``,
  ``validate_mapping(mapping, silver, json_schema)``, raising
  ``EngineContractError`` on any schema or cross-check violation.
"""

from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path

import pytest

from metricmine.engine.emit import build_emission_set
from metricmine.engine.reader import (
    EngineContractError,
    load_inputs,
    validate_mapping,
)

REPO = Path(__file__).resolve().parents[1]
FIXTURES = REPO / "tests" / "golden" / "emitted"

HEADER_SQL = "-- Generated by metricmine-engine v"
HEADER_YML = "# Generated by metricmine-engine v"


def test_emission_matches_golden_fixtures() -> None:
    """Same contracts in, byte-identical files out (D-29; Q8 fixed point)."""
    emitted = build_emission_set(REPO)
    fixture_names = sorted(p.name for p in FIXTURES.iterdir())
    assert sorted(emitted) == fixture_names
    for name, content in emitted.items():
        expected = (FIXTURES / name).read_text(encoding="utf-8")
        assert content == expected, f"{name} diverges from its golden fixture"


def test_emission_is_deterministic() -> None:
    """Two independent runs produce byte-identical sets."""
    first = build_emission_set(REPO)
    second = build_emission_set(REPO)
    assert first == second


def test_generated_by_headers_lead_every_file() -> None:
    """Engine-owned marker, exact form, first line of every emitted file
    (docs/spec/engine.md §5; D-09)."""
    emitted = build_emission_set(REPO)
    for name, content in emitted.items():
        if name.endswith(".sql"):
            assert content.startswith(HEADER_SQL), name
        elif name.endswith(".yml"):
            assert content.startswith(HEADER_YML), name
        else:
            assert name == "ownership-manifest.json"


def test_ownership_manifest_hashes_the_fixed_point() -> None:
    """The manifest covers every emitted file except itself, with sha256
    over the emitted bytes (docs/spec/engine.md §5)."""
    emitted = build_emission_set(REPO)
    manifest = json.loads(emitted["ownership-manifest.json"])
    listed = manifest["files"]
    expected_paths = {
        f"transform/models/gold/{name}"
        for name in emitted
        if name != "ownership-manifest.json"
    }
    assert set(listed) == expected_paths
    for path, digest in listed.items():
        content = emitted[path.rsplit("/", 1)[1]]
        actual = "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()
        assert digest == actual, f"{path} checksum mismatch"
    assert manifest["engine_version"]
    assert manifest["sources"]["mapping_contract"]["version"] == "1.0.0"
    assert manifest["sources"]["gold_contract"]["version"] == "1.0.0"


def _inputs():
    return load_inputs(REPO)


def test_reader_accepts_the_committed_mapping_contract() -> None:
    inputs = _inputs()
    validate_mapping(inputs.mapping, inputs.silver, inputs.json_schema)


@pytest.mark.parametrize(
    "mutate, reason",
    [
        (
            lambda doc: doc["schema"][0].__setitem__("quality", []),
            "quality rules are dead letters in a mapping contract (F-12)",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__("name", "dim_invoice_lines"),
            "reserved category-name pattern (F-12 collision guard)",
        ),
        (
            lambda doc: doc["schema"][0]["grain"]["degenerateIdentifiers"][0][
                "of"
            ].append("no_such_column"),
            "derived-of references an undeclared field",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__("timeColumn", "quantity"),
            "timeColumn must carry mappingRole time",
        ),
        (
            lambda doc: doc["schema"][0].__setitem__(
                "sourceTable", "silver.no_such_table"
            ),
            "sourceTable must name the silver contract's object",
        ),
    ],
)
def test_reader_rejects_invalid_mapping_contracts(mutate, reason) -> None:
    """Fail-closed static groundedness (docs/spec/engine.md §5)."""
    inputs = _inputs()
    broken = copy.deepcopy(inputs.mapping)
    mutate(broken)
    with pytest.raises(EngineContractError):
        validate_mapping(broken, inputs.silver, inputs.json_schema)
