-- PROBE ARTIFACT (P2/P3). Emitted-style gold model standing in for a
-- values dimension. Generated by: metricmine-engine 0.0.0-probe from
-- contract gold_probe_star v0.0.1 (mock header; the real header format is
-- an engine-spec decision, Q5).

select
    cast('a3f2' as varchar)              as value_hash_id,
    cast('{"probe":"row"}' as varchar)   as payload
