-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_probe_star@0.0.1 (model: dim_probe_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_probe_values__custom_sql", "contract_versions": ["0.0.1"], "generated": true, "include_in_tests": true, "model": "dim_probe_values", "description": "Matched-object rule; must generate and run."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM gold.dim_probe_values WHERE value_hash_id IS NULL
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
