-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_ourairports_airports@1.0.0 (model: silver_ourairports_airports)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_ourairports_airports__longitude_deg__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_ourairports_airports", "field": "longitude_deg", "description": "Longitude stays within the WGS84 range."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_ourairports_airports WHERE longitude_deg < -180 or longitude_deg > 180
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
