-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_ourairports_airports@1.0.0 (model: silver_ourairports_airports)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_ourairports_airports__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_ourairports_airports", "description": "Grain enforcement: no duplicate (iata_code) combinations. Declared at error severity because the primaryKey-flag composite test generates at warn severity at datacontract-cli 1.0.12 (rule 5: uniqueness as a test, never a trusted constraint)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT iata_code
  FROM silver.silver_ourairports_airports
  GROUP BY iata_code
  HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
