-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_flights@1.0.0 (model: silver_nyc_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_flights__tail_number__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_flights", "field": "tail_number", "description": "Conformed key tail_number: every value matches ^[A-Z0-9]{2,6}$ (the K1 normalization rule, D-41)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_nyc_flights WHERE tail_number IS NOT NULL AND NOT regexp_matches(tail_number, '^[A-Z0-9]{2,6}$')
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
