-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_flights@1.0.0 (model: silver_nyc_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_flights__origin_airport__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_flights", "field": "origin_airport", "description": "Conformed key airport_iata: every value matches ^[A-Z]{3}$ (the K1 normalization rule, D-41)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_nyc_flights WHERE NOT regexp_matches(origin_airport, '^[A-Z]{3}$')
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
