-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_flights@1.0.0 (model: silver_nyc_flights, check: unique_combination)
{{ config(severity='warn', meta={"datacontract_cli": {"check": "silver_nyc_flights__model_unique_combination", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_flights", "description": "Check that model silver_nyc_flights has a unique combination of columns flight_date, carrier_code, flight_number, origin_airport, sched_dep_hhmm"}}) }}
SELECT "flight_date", "carrier_code", "flight_number", "origin_airport", "sched_dep_hhmm"
FROM {{ ref('silver_nyc_flights') }}
GROUP BY "flight_date", "carrier_code", "flight_number", "origin_airport", "sched_dep_hhmm"
HAVING COUNT(*) > 1
