-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_weather@1.0.0 (model: silver_nyc_weather, check: unique_combination)
{{ config(severity='warn', meta={"datacontract_cli": {"check": "silver_nyc_weather__model_unique_combination", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_weather", "description": "Check that model silver_nyc_weather has a unique combination of columns airport_code, observed_hour_utc"}}) }}
SELECT "airport_code", "observed_hour_utc"
FROM {{ ref('silver_nyc_weather') }}
GROUP BY "airport_code", "observed_hour_utc"
HAVING COUNT(*) > 1
