-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_weather@1.0.0 (model: silver_nyc_weather)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_weather__precip_inches__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_weather", "field": "precip_inches", "description": "Precipitation is never negative."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_nyc_weather WHERE precip_inches < 0
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
