-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_weather@1.0.0 (model: silver_nyc_weather)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_weather__observed_hour_local__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_weather", "field": "observed_hour_local", "description": "The local hour agrees with observed_hour_utc rendered in America/New_York on every row (the time zone consistency rule)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_nyc_weather WHERE observed_hour_local != extract(hour from (observed_hour_utc at time zone 'UTC' at time zone 'America/New_York'))
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
