-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_nyc_weather@1.0.0 (model: silver_nyc_weather)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_nyc_weather__humidity_pct__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_nyc_weather", "field": "humidity_pct", "description": "Relative humidity stays within 0 and 100 percent."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_nyc_weather WHERE humidity_pct < 0 or humidity_pct > 100
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
