-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_ourairports_runways@1.0.0 (model: silver_ourairports_runways)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_ourairports_runways__length_ft__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_ourairports_runways", "field": "length_ft", "description": "Runway length is positive where recorded."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_ourairports_runways WHERE length_ft <= 0
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
