-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_invoice_lines@1.1.1 (model: silver_invoice_lines)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_invoice_lines__row_count", "contract_versions": ["1.1.1"], "generated": true, "include_in_tests": true, "model": "silver_invoice_lines", "description": "The table is never empty; the committed sample yields tens of thousands of surviving lines.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('silver_invoice_lines') }}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <= 0
