-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_invoice_lines@1.3.0 (model: silver_invoice_lines, check: unique_combination)
{{ config(severity='warn', meta={"datacontract_cli": {"check": "silver_invoice_lines__model_unique_combination", "contract_versions": ["1.3.0"], "generated": true, "include_in_tests": true, "model": "silver_invoice_lines", "description": "Check that model silver_invoice_lines has a unique combination of columns invoice_id, stock_code, quantity, unit_price"}}) }}
SELECT "invoice_id", "stock_code", "quantity", "unit_price"
FROM {{ ref('silver_invoice_lines') }}
GROUP BY "invoice_id", "stock_code", "quantity", "unit_price"
HAVING COUNT(*) > 1
