-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_invoice_lines@1.3.0 (model: silver_invoice_lines)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_invoice_lines__unit_price__custom_sql", "contract_versions": ["1.3.0"], "generated": true, "include_in_tests": true, "model": "silver_invoice_lines", "field": "unit_price", "description": "Unit price is never negative."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM silver.silver_invoice_lines WHERE unit_price < 0
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
