-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_invoice_lines@1.1.0 (model: silver_invoice_lines)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_invoice_lines__custom_sql", "contract_versions": ["1.1.0"], "generated": true, "include_in_tests": true, "model": "silver_invoice_lines", "description": "Grain enforcement: no duplicate (invoice_id, stock_code, quantity, unit_price) combinations. Declared at error severity because the primaryKey-flag composite test generates at hardcoded warn severity at datacontract-cli 1.0.12 and cannot redden a gate; this rule is the enforcing twin (rule 5: uniqueness as a test, never a trusted constraint).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT invoice_id, stock_code, quantity, unit_price
  FROM silver.silver_invoice_lines
  GROUP BY invoice_id, stock_code, quantity, unit_price
  HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
