-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.0.0 (model: dim_timeframe_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_timeframe_values__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "dim_timeframe_values", "description": "Content-key uniqueness: the error-severity twin of the primaryKey flag.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT timeframe_hash_id FROM gold.dim_timeframe_values
  GROUP BY timeframe_hash_id HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
