-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.0.0 (model: dim_source_columns)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_source_columns__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "dim_source_columns", "description": "Schema-key uniqueness: the error-severity twin of the primaryKey flag.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT source_col_hash_id FROM gold.dim_source_columns
  GROUP BY source_col_hash_id HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
