-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.2.0 (model: fact_invoice_lines_values, check: unique_combination)
{{ config(severity='warn', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__model_unique_combination", "contract_versions": ["1.2.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "Check that model fact_invoice_lines_values has a unique combination of columns fact_hash_id, source_hash_id, timeframe_hash_id, dim_hash_id"}}) }}
SELECT "fact_hash_id", "source_hash_id", "timeframe_hash_id", "dim_hash_id"
FROM {{ ref('fact_invoice_lines_values') }}
GROUP BY "fact_hash_id", "source_hash_id", "timeframe_hash_id", "dim_hash_id"
HAVING COUNT(*) > 1
