-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.4.0 (model: context_registry)
{{ config(severity='error', meta={"datacontract_cli": {"check": "context_registry__custom_sql", "contract_versions": ["1.4.0"], "generated": true, "include_in_tests": true, "model": "context_registry", "description": "C3 registry coverage: every schema key present in gold exists in context_registry. ref()-edged per F-19 so the generated test schedules after every columns dimension and the registry on a fresh warehouse.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT dim_col_hash_id AS schema_key FROM {{ ref('dim_invoice_lines_columns') }}
  UNION
  SELECT source_col_hash_id FROM {{ ref('dim_source_columns') }}
  UNION
  SELECT run_col_hash_id FROM {{ ref('dim_run_columns') }}
  UNION
  SELECT timeframe_col_hash_id FROM {{ ref('dim_timeframe_columns') }}
) gold_keys
WHERE NOT EXISTS (
  SELECT 1 FROM {{ ref('context_registry') }} r
  WHERE r.schema_key = gold_keys.schema_key
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
