-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "Grain enforcement: zero duplicate (fact, source, timeframe, dim) key tuples, the error-severity twin of the composite primaryKey flag, whose generated test is warn-hardcoded (F-08).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT fact_hash_id, source_hash_id, timeframe_hash_id, dim_hash_id
  FROM {{ ref('fact_invoice_lines_values') }}
  {% if var('mm_batch_floor', none) is not none %} WHERE captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
  GROUP BY fact_hash_id, source_hash_id, timeframe_hash_id, dim_hash_id
  HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
