-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.1.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.1.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "C1 conservation: silver rows in scope equal fact rows at transaction grain (44,721 + 0 excluded = 44,721 at v1.1.0 over the committed sample). Schema-qualified silver reference by design: a missing referenced table catalog-errors loudly rather than skipping (F-08).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT (SELECT COUNT(*) FROM silver.silver_invoice_lines)
     - (SELECT COUNT(*) FROM {{ ref('fact_invoice_lines_values') }})
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
