-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.5.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.5.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "C2: every dim_hash_id resolves in dim_invoice_lines_values."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('fact_invoice_lines_values') }} f
WHERE NOT EXISTS (
  SELECT 1 FROM {{ ref('dim_invoice_lines_values') }} d
  WHERE d.dim_hash_id = f.dim_hash_id
)
{% if var('mm_batch_floor', none) is not none %} AND f.captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
