-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: dim_run_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_run_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "dim_run_values", "description": "C4: every run payload parses as valid JSON."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('dim_run_values') }}
WHERE NOT json_valid(run_values)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
