-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.5.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.5.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "C4: every measure payload parses as valid JSON."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('fact_invoice_lines_values') }}
WHERE NOT json_valid(fact_values)
{% if var('mm_batch_floor', none) is not none %} AND captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
