-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.3.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.3.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "C2: every run_hash_id (non-key) resolves in dim_run_values.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('fact_invoice_lines_values') }} f
WHERE NOT EXISTS (
  SELECT 1 FROM {{ ref('dim_run_values') }} d
  WHERE d.run_hash_id = f.run_hash_id
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
