-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.4.0 (model: dim_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_invoice_lines_values__custom_sql", "contract_versions": ["1.4.0"], "generated": true, "include_in_tests": true, "model": "dim_invoice_lines_values", "description": "Content-key uniqueness: the error-severity twin of the primaryKey flag.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT dim_hash_id FROM {{ ref('dim_invoice_lines_values') }}
  {% if var('mm_batch_floor', none) is not none %} WHERE captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
  GROUP BY dim_hash_id HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
