-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: fact_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_invoice_lines_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "fact_invoice_lines_values", "description": "C5 field-level reconciliation: every silver row joins the typed surface on the derived line identity and every mapped field matches its served value (text fields lowercased per D-18; invoiced_at at the declared minute grain; null-safe compare). The Session J runbook validation, ten matching counts of 44,721 over the committed sample, promoted to a standing test (V1-06). Zero rows may disagree.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT *, sha256(lower(to_json(struct_pack(
    invoice_id := cast(invoice_id as varchar),
    quantity := cast(quantity as varchar),
    stock_code := cast(stock_code as varchar),
    unit_price := cast(unit_price as varchar)
  )))) AS line_identity
  FROM silver.silver_invoice_lines
  {% if var('mm_batch_floor', none) is not none %} WHERE captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
) s
LEFT JOIN {{ ref('vw_invoice_lines_typed') }} v USING (line_identity)
WHERE v.invoice_id IS DISTINCT FROM lower(s.invoice_id)
   OR v.is_cancellation IS DISTINCT FROM s.is_cancellation
   OR v.stock_code IS DISTINCT FROM lower(s.stock_code)
   OR v.product_description IS DISTINCT FROM lower(s.product_description)
   OR v.customer_id IS DISTINCT FROM s.customer_id
   OR v.country IS DISTINCT FROM lower(s.country)
   OR v.invoiced_at IS DISTINCT FROM date_trunc('minute', s.invoiced_at)
   OR v.quantity IS DISTINCT FROM s.quantity
   OR v.unit_price IS DISTINCT FROM s.unit_price
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
