-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.5.0 (model: dim_timeframe_columns)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_timeframe_columns__row_count", "contract_versions": ["1.5.0"], "generated": true, "include_in_tests": true, "model": "dim_timeframe_columns", "description": "The dimension is never empty once the star builds."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('dim_timeframe_columns') }}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <= 0
