-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: context_registry)
{{ config(severity='error', meta={"datacontract_cli": {"check": "context_registry__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "context_registry", "description": "Schema-key uniqueness: the error-severity twin of the primaryKey flag (its generated test is warn-hardcoded, F-08).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT schema_key FROM {{ ref('context_registry') }}
  GROUP BY schema_key HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
