-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.3.0 (model: context_registry)
{{ config(severity='error', meta={"datacontract_cli": {"check": "context_registry__row_count", "contract_versions": ["1.3.0"], "generated": true, "include_in_tests": true, "model": "context_registry", "description": "The registry is never empty once the star builds."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('context_registry') }}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <= 0
