-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: fact_flights_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_flights_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "fact_flights_values", "description": "C1 conservation: silver rows in scope equal fact rows at transaction grain. Schema-qualified silver reference by design: a missing referenced table catalog-errors loudly rather than skipping (F-08).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT (SELECT COUNT(*) FROM silver.silver_flights)
     - (SELECT COUNT(*) FROM {{ ref('fact_flights_values') }})
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
