-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.5.0 (model: context_registry)
{{ config(severity='error', meta={"datacontract_cli": {"check": "context_registry__custom_sql", "contract_versions": ["1.5.0"], "generated": true, "include_in_tests": true, "model": "context_registry", "description": "Registry JSON validity (the C4 discipline applied to compiled context): every compiled_context parses as valid JSON.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('context_registry') }}
WHERE NOT json_valid(compiled_context)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
