-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: fact_flights_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_flights_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "fact_flights_values", "description": "C5 field-level reconciliation: every silver row joins the typed surface on the derived flight_identity and every mapped field matches its served value (text fields lowercased per D-18; departure_hour_utc at the declared hour grain; null-safe compare). Zero rows may disagree.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT *, sha256(lower(to_json(struct_pack(
    carrier_code := cast(carrier_code as varchar),
    flight_date := cast(flight_date as varchar),
    flight_number := cast(flight_number as varchar),
    origin_airport := cast(origin_airport as varchar),
    sched_dep_hhmm := cast(sched_dep_hhmm as varchar)
  )))) AS flight_identity
  FROM silver.silver_flights
  {% if var('mm_batch_floor', none) is not none %} WHERE captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
) s
LEFT JOIN {{ ref('vw_flights_typed') }} v USING (flight_identity)
WHERE v.flight_date IS DISTINCT FROM s.flight_date
   OR v.carrier_code IS DISTINCT FROM lower(s.carrier_code)
   OR v.flight_number IS DISTINCT FROM s.flight_number
   OR v.origin_airport IS DISTINCT FROM lower(s.origin_airport)
   OR v.sched_dep_hhmm IS DISTINCT FROM s.sched_dep_hhmm
   OR v.dest_airport IS DISTINCT FROM lower(s.dest_airport)
   OR v.tail_number IS DISTINCT FROM lower(s.tail_number)
   OR v.is_cancelled IS DISTINCT FROM s.is_cancelled
   OR v.dep_hhmm IS DISTINCT FROM s.dep_hhmm
   OR v.arr_hhmm IS DISTINCT FROM s.arr_hhmm
   OR v.sched_arr_hhmm IS DISTINCT FROM s.sched_arr_hhmm
   OR v.sched_dep_hour_local IS DISTINCT FROM s.sched_dep_hour_local
   OR v.sched_dep_minute_local IS DISTINCT FROM s.sched_dep_minute_local
   OR v.carrier_name IS DISTINCT FROM lower(s.carrier_name)
   OR v.aircraft_manufacturer IS DISTINCT FROM lower(s.aircraft_manufacturer)
   OR v.aircraft_model IS DISTINCT FROM lower(s.aircraft_model)
   OR v.aircraft_manufacture_year IS DISTINCT FROM s.aircraft_manufacture_year
   OR v.aircraft_seat_count IS DISTINCT FROM s.aircraft_seat_count
   OR v.aircraft_engine_type IS DISTINCT FROM lower(s.aircraft_engine_type)
   OR v.origin_airport_name IS DISTINCT FROM lower(s.origin_airport_name)
   OR v.origin_municipality IS DISTINCT FROM lower(s.origin_municipality)
   OR v.origin_elevation_ft IS DISTINCT FROM s.origin_elevation_ft
   OR v.origin_longest_runway_ft IS DISTINCT FROM s.origin_longest_runway_ft
   OR v.dest_airport_name IS DISTINCT FROM lower(s.dest_airport_name)
   OR v.dest_municipality IS DISTINCT FROM lower(s.dest_municipality)
   OR v.dest_iso_region IS DISTINCT FROM lower(s.dest_iso_region)
   OR v.dest_elevation_ft IS DISTINCT FROM s.dest_elevation_ft
   OR v.dest_longest_runway_ft IS DISTINCT FROM s.dest_longest_runway_ft
   OR v.departure_hour_utc IS DISTINCT FROM date_trunc('hour', s.departure_hour_utc)
   OR v.dep_delay_minutes IS DISTINCT FROM s.dep_delay_minutes
   OR v.arr_delay_minutes IS DISTINCT FROM s.arr_delay_minutes
   OR v.air_time_minutes IS DISTINCT FROM s.air_time_minutes
   OR v.distance_miles IS DISTINCT FROM s.distance_miles
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
