-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: dim_timeframe_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_timeframe_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "dim_timeframe_values", "description": "C4: every timeframe payload parses as valid JSON."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('dim_timeframe_values') }}
WHERE NOT json_valid(timeframe_values)
{% if var('mm_batch_floor', none) is not none %} AND captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
