-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.1.0 (model: dim_source_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_source_values__custom_sql", "contract_versions": ["1.1.0"], "generated": true, "include_in_tests": true, "model": "dim_source_values", "description": "Content-key uniqueness: the error-severity twin of the primaryKey flag (its generated test is warn-hardcoded, F-08).\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT source_hash_id FROM {{ ref('dim_source_values') }}
  GROUP BY source_hash_id HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
