-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.2.0 (model: dim_run_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_run_values__custom_sql", "contract_versions": ["1.2.0"], "generated": true, "include_in_tests": true, "model": "dim_run_values", "description": "Content-key uniqueness: the error-severity twin of the primaryKey flag.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT run_hash_id FROM {{ ref('dim_run_values') }}
  GROUP BY run_hash_id HAVING COUNT(*) > 1
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
