-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.6.0 (model: fact_airport_weather_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "fact_airport_weather_values__custom_sql", "contract_versions": ["1.6.0"], "generated": true, "include_in_tests": true, "model": "fact_airport_weather_values", "description": "C5 field-level reconciliation: every silver row joins the typed surface on the derived observation_identity and every mapped field matches its served value (text fields lowercased per D-18; observed_hour_utc at the declared hour grain; null-safe compare). Zero rows may disagree.\n"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT *, sha256(lower(to_json(struct_pack(
    airport_code := cast(airport_code as varchar),
    observed_hour_utc := cast(observed_hour_utc as varchar)
  )))) AS observation_identity
  FROM silver.silver_airport_weather
  {% if var('mm_batch_floor', none) is not none %} WHERE captured_at >= TIMESTAMP '{{ var("mm_batch_floor") }}' {% endif %}
) s
LEFT JOIN {{ ref('vw_airport_weather_typed') }} v USING (observation_identity)
WHERE v.airport_code IS DISTINCT FROM lower(s.airport_code)
   OR v.observed_date_local IS DISTINCT FROM s.observed_date_local
   OR v.observed_hour_local IS DISTINCT FROM s.observed_hour_local
   OR v.airport_name IS DISTINCT FROM lower(s.airport_name)
   OR v.airport_municipality IS DISTINCT FROM lower(s.airport_municipality)
   OR v.airport_elevation_ft IS DISTINCT FROM s.airport_elevation_ft
   OR v.airport_longest_runway_ft IS DISTINCT FROM s.airport_longest_runway_ft
   OR v.observed_hour_utc IS DISTINCT FROM date_trunc('hour', s.observed_hour_utc)
   OR v.temp_f IS DISTINCT FROM s.temp_f
   OR v.dewpoint_f IS DISTINCT FROM s.dewpoint_f
   OR v.humidity_pct IS DISTINCT FROM s.humidity_pct
   OR v.wind_dir_degrees IS DISTINCT FROM s.wind_dir_degrees
   OR v.wind_speed_mph IS DISTINCT FROM s.wind_speed_mph
   OR v.wind_gust_mph IS DISTINCT FROM s.wind_gust_mph
   OR v.precip_inches IS DISTINCT FROM s.precip_inches
   OR v.pressure_mb IS DISTINCT FROM s.pressure_mb
   OR v.visibility_miles IS DISTINCT FROM s.visibility_miles
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
