-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: gold_unified_event_star@1.0.0 (model: dim_invoice_lines_values)
{{ config(severity='error', meta={"datacontract_cli": {"check": "dim_invoice_lines_values__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "dim_invoice_lines_values", "description": "C4: every dimension payload parses as valid JSON."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM gold.dim_invoice_lines_values
WHERE NOT json_valid(dim_values)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
