-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_flights@1.0.0 (model: silver_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_flights__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_flights", "description": "Join completeness, aircraft: at least 0.80 of rows resolve tail_number in silver_nyc_planes.tail_number (measured 0.8396 at profile v0001; fleet numbers and missing tail numbers leave 16 percent unresolved). The M2 floor of D-41, declared below the measured value so a reference refresh that adds coverage passes and one that loses it fails."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT 1 FROM {{ ref('silver_flights') }}
  HAVING SUM(CASE WHEN aircraft_manufacturer IS NOT NULL THEN 1 ELSE 0 END) * 1.0 / COUNT(*) < 0.8
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
