-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_flights@1.0.0 (model: silver_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_flights__carrier_code__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_flights", "field": "carrier_code", "description": "Conformed key carrier_code: every value matches ^[A-Z0-9]{2,3}$ (the K1 normalization rule, D-41)."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('silver_flights') }} WHERE NOT regexp_matches(carrier_code, '^[A-Z0-9]{2,3}$')
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
