-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_flights@1.0.0 (model: silver_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_flights__row_count", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_flights", "description": "The table is never empty; the committed extract lands every row."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('silver_flights') }}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <= 0
