-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: silver_flights@1.0.0 (model: silver_flights)
{{ config(severity='error', meta={"datacontract_cli": {"check": "silver_flights__custom_sql", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "silver_flights", "description": "Join completeness, dest: at least 0.97 of rows resolve dest_airport in silver_ourairports_airports.iata_code (measured 0.9791 at profile v0001; PBI does not resolve in the 2026 reference). The M2 floor of D-41, declared below the measured value so a reference refresh that adds coverage passes and one that loses it fails."}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM (
  SELECT 1 FROM {{ ref('silver_flights') }}
  HAVING SUM(CASE WHEN dest_airport_name IS NOT NULL THEN 1 ELSE 0 END) * 1.0 / COUNT(*) < 0.97
)
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <> 0
