-- Generated by metricmine-engine v0.2.0 from gold_invoice_lines_mapping v1.0.0 + gold_unified_event_star v1.1.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

select
    '8f99de0c5aa34c2e3e2e66890f7b986f0c2d39b9276b901f1232efd0ebcc0dd8' as timeframe_col_hash_id,
    '["invoiced_at"]' as timeframe_columns,
    current_localtimestamp()    as loaded_at
