-- Generated by metricmine-engine v0.4.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.5.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_invoice_lines') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

payloads as (

    select
        lower(to_json(struct_pack(
            invoiced_at := cast(date_trunc('minute', invoiced_at) as varchar)
        ))) as timeframe_values,
        captured_at
    from source

),

grouped as (

    select
        timeframe_values,
        min(captured_at) as captured_at
    from payloads
    group by timeframe_values

)

select
    sha256(timeframe_values)    as timeframe_hash_id,
    '8f99de0c5aa34c2e3e2e66890f7b986f0c2d39b9276b901f1232efd0ebcc0dd8' as timeframe_col_hash_id,
    timeframe_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.timeframe_hash_id = sha256(grouped.timeframe_values)
)
{% endif %}
