-- Generated by metricmine-engine v0.5.0 from gold_unified_event_star v1.5.0 over 1 mapping contract (gold_invoice_lines_mapping v1.1.1).
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with manifest as (

    select
        'dacafb1855b6ce1628eb3be9b6c8eeeedc3d4f45454a6fd87093deda9d0cc848' as run_col_hash_id,
        '["mapping_contract_name","mapping_contract_version","engine_version"]' as run_columns

)

select
    run_col_hash_id,
    run_columns,
    current_localtimestamp()    as loaded_at
from manifest
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.run_col_hash_id = manifest.run_col_hash_id
)
{% endif %}
