-- Generated by metricmine-engine v0.1.0 from gold_invoice_lines_mapping v1.0.0 + gold_unified_event_star v1.0.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with manifests as (

    select '["invoice_id","is_cancellation","stock_code","product_description","customer_id","line_identity"]' as dim_columns, '0f6d343a59567a7717ef57a9ac17d2ff90355dc1f57d11c100867fddfb866108' as dim_col_hash_id
    union all
    select '["quantity","unit_price"]', '9dbc23cabca765eeaed72eb8161c90b5ae7857f81031656002f03e5bd9d99319'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
