-- Generated by metricmine-engine v0.5.0 from gold_flights_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with manifests as (

    select '["flight_date","carrier_code","flight_number","origin_airport","sched_dep_hhmm","dest_airport","tail_number","is_cancelled","dep_hhmm","arr_hhmm","sched_arr_hhmm","sched_dep_hour_local","sched_dep_minute_local","carrier_name","aircraft_manufacturer","aircraft_model","aircraft_manufacture_year","aircraft_seat_count","aircraft_engine_type","origin_airport_name","origin_municipality","origin_elevation_ft","origin_longest_runway_ft","dest_airport_name","dest_municipality","dest_iso_region","dest_elevation_ft","dest_longest_runway_ft","flight_identity"]' as dim_columns, '5849da18299cc930cecf084f9bc784819669d8fed49b8e560abb62c17b21c8e6' as dim_col_hash_id
    union all
    select '["dep_delay_minutes","arr_delay_minutes","air_time_minutes","distance_miles"]', 'bbcae4efb6f4db6e756283463eb71e7052195caf2586f795317836b644bc7ddf'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.dim_col_hash_id = manifests.dim_col_hash_id
)
{% endif %}
