-- Generated by metricmine-engine v0.3.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.4.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with source as (

    select * from {{ ref('silver_invoice_lines') }}

),

payloads as (

    select distinct lower(to_json(struct_pack(
            country := cast(country as varchar),
            customer_id := cast(customer_id as varchar),
            invoice_id := cast(invoice_id as varchar),
            is_cancellation := cast(is_cancellation as varchar),
            line_identity := sha256(lower(to_json(struct_pack(
                invoice_id := cast(invoice_id as varchar),
                quantity := cast(quantity as varchar),
                stock_code := cast(stock_code as varchar),
                unit_price := cast(unit_price as varchar)
            )))),
            product_description := cast(product_description as varchar),
            stock_code := cast(stock_code as varchar)
        ))) as dim_values
    from source

)

select
    sha256(dim_values)          as dim_hash_id,
    '2d27bd360b5092ff22047c65407ff05699afad98f455de2409665a5950a05e82' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at
from payloads
