-- Generated by metricmine-engine v0.4.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.5.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with manifest as (

    select
        '61e74223d961799a0f8b12bf9045b422b5cad4fc9273e1ce3f65eb07966a2e1f' as source_col_hash_id,
        '["source_table"]' as source_columns

)

select
    source_col_hash_id,
    source_columns,
    current_localtimestamp()    as loaded_at
from manifest
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.source_col_hash_id = manifest.source_col_hash_id
)
{% endif %}
