-- Generated by metricmine-engine v0.2.0 from gold_invoice_lines_mapping v1.0.0 + gold_unified_event_star v1.1.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

select
    'dacafb1855b6ce1628eb3be9b6c8eeeedc3d4f45454a6fd87093deda9d0cc848' as run_col_hash_id,
    '["mapping_contract_name","mapping_contract_version","engine_version"]' as run_columns,
    current_localtimestamp()    as loaded_at
