-- Generated by metricmine-engine v0.5.0 from gold_unified_event_star v1.6.0 over 3 mapping contracts (gold_airport_weather_mapping v1.0.0, gold_flights_mapping v1.0.0, gold_invoice_lines_mapping v1.1.1).
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with manifest as (

    select
        '882bb5e70283711a0c90460b64b632f83786eaf265e1e044bfbe288e6144ae98' as timeframe_col_hash_id,
        '["grain","period_start"]' as timeframe_columns

)

select
    timeframe_col_hash_id,
    timeframe_columns,
    current_localtimestamp()    as loaded_at
from manifest
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.timeframe_col_hash_id = manifest.timeframe_col_hash_id
)
{% endif %}
