-- Generated by metricmine-engine v0.5.0 from gold_flights_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_flights') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

payloads as (

    select
        lower(to_json(struct_pack(
            aircraft_engine_type := cast(aircraft_engine_type as varchar),
            aircraft_manufacture_year := cast(aircraft_manufacture_year as varchar),
            aircraft_manufacturer := cast(aircraft_manufacturer as varchar),
            aircraft_model := cast(aircraft_model as varchar),
            aircraft_seat_count := cast(aircraft_seat_count as varchar),
            arr_hhmm := cast(arr_hhmm as varchar),
            carrier_code := cast(carrier_code as varchar),
            carrier_name := cast(carrier_name as varchar),
            dep_hhmm := cast(dep_hhmm as varchar),
            dest_airport := cast(dest_airport as varchar),
            dest_airport_name := cast(dest_airport_name as varchar),
            dest_elevation_ft := cast(dest_elevation_ft as varchar),
            dest_iso_region := cast(dest_iso_region as varchar),
            dest_longest_runway_ft := cast(dest_longest_runway_ft as varchar),
            dest_municipality := cast(dest_municipality as varchar),
            flight_date := cast(flight_date as varchar),
            flight_identity := sha256(lower(to_json(struct_pack(
                carrier_code := cast(carrier_code as varchar),
                flight_date := cast(flight_date as varchar),
                flight_number := cast(flight_number as varchar),
                origin_airport := cast(origin_airport as varchar),
                sched_dep_hhmm := cast(sched_dep_hhmm as varchar)
            )))),
            flight_number := cast(flight_number as varchar),
            is_cancelled := cast(is_cancelled as varchar),
            origin_airport := cast(origin_airport as varchar),
            origin_airport_name := cast(origin_airport_name as varchar),
            origin_elevation_ft := cast(origin_elevation_ft as varchar),
            origin_longest_runway_ft := cast(origin_longest_runway_ft as varchar),
            origin_municipality := cast(origin_municipality as varchar),
            sched_arr_hhmm := cast(sched_arr_hhmm as varchar),
            sched_dep_hhmm := cast(sched_dep_hhmm as varchar),
            sched_dep_hour_local := cast(sched_dep_hour_local as varchar),
            sched_dep_minute_local := cast(sched_dep_minute_local as varchar),
            tail_number := cast(tail_number as varchar)
        ))) as dim_values,
        captured_at
    from source

),

grouped as (

    select
        dim_values,
        min(captured_at) as captured_at
    from payloads
    group by dim_values

)

select
    sha256(dim_values)          as dim_hash_id,
    '5849da18299cc930cecf084f9bc784819669d8fed49b8e560abb62c17b21c8e6' as dim_col_hash_id,
    dim_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from grouped
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.dim_hash_id = sha256(grouped.dim_values)
)
{% endif %}
