-- Generated by metricmine-engine v0.5.0 from gold_unified_event_star v1.6.0 over 3 mapping contracts (gold_airport_weather_mapping v1.0.0, gold_flights_mapping v1.0.0, gold_invoice_lines_mapping v1.1.1).
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with payloads as (

    select lower(to_json(struct_pack(
            engine_version := '0.5.0',
            mapping_contract_name := 'gold_airport_weather_mapping',
            mapping_contract_version := '1.0.0'
        ))) as run_values
    union all
    select lower(to_json(struct_pack(
            engine_version := '0.5.0',
            mapping_contract_name := 'gold_flights_mapping',
            mapping_contract_version := '1.0.0'
        ))) as run_values
    union all
    select lower(to_json(struct_pack(
            engine_version := '0.5.0',
            mapping_contract_name := 'gold_invoice_lines_mapping',
            mapping_contract_version := '1.1.1'
        ))) as run_values

)

select
    sha256(run_values)      as run_hash_id,
    'dacafb1855b6ce1628eb3be9b6c8eeeedc3d4f45454a6fd87093deda9d0cc848' as run_col_hash_id,
    run_values,
    current_localtimestamp()    as loaded_at
from payloads
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.run_hash_id = sha256(payloads.run_values)
)
{% endif %}
