-- Generated by metricmine-engine v0.3.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.4.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with manifests as (

    select '["invoice_id","is_cancellation","stock_code","product_description","customer_id","country","line_identity"]' as dim_columns, '2d27bd360b5092ff22047c65407ff05699afad98f455de2409665a5950a05e82' as dim_col_hash_id
    union all
    select '["quantity","unit_price"]', '9dbc23cabca765eeaed72eb8161c90b5ae7857f81031656002f03e5bd9d99319'

)

select
    dim_col_hash_id,
    dim_columns,
    current_localtimestamp()    as loaded_at
from manifests
