-- Generated by metricmine-engine v0.3.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.3.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

with source as (

    select * from {{ ref('silver_invoice_lines') }}

),

keyed as (

    select
        lower(to_json(struct_pack(
            quantity := cast(quantity as varchar),
            unit_price := cast(unit_price as varchar)
        ))) as fact_values,
        lower(to_json(struct_pack(
            country := cast(country as varchar),
            customer_id := cast(customer_id as varchar),
            invoice_id := cast(invoice_id as varchar),
            is_cancellation := cast(is_cancellation as varchar),
            line_identity := sha256(lower(to_json(struct_pack(
                invoice_id := cast(invoice_id as varchar),
                quantity := cast(quantity as varchar),
                stock_code := cast(stock_code as varchar),
                unit_price := cast(unit_price as varchar)
            )))),
            product_description := cast(product_description as varchar),
            stock_code := cast(stock_code as varchar)
        ))) as dim_payload,
        lower(to_json(struct_pack(
            invoiced_at := cast(date_trunc('minute', invoiced_at) as varchar)
        ))) as timeframe_payload
    from source

)

select
    sha256(fact_values)         as fact_hash_id,
    sha256(lower(to_json(struct_pack(
            source_table := 'silver.silver_invoice_lines'
        )))) as source_hash_id,
    sha256(timeframe_payload)   as timeframe_hash_id,
    sha256(dim_payload)         as dim_hash_id,
    sha256(lower(to_json(struct_pack(
            engine_version := '0.3.0',
            mapping_contract_name := 'gold_invoice_lines_mapping',
            mapping_contract_version := '1.1.1'
        )))) as run_hash_id,
    '9dbc23cabca765eeaed72eb8161c90b5ae7857f81031656002f03e5bd9d99319' as fact_col_hash_id,
    fact_values,
    current_localtimestamp()    as loaded_at
from keyed
