-- Generated by metricmine-engine v0.5.0 from gold_flights_mapping v1.0.0 + gold_unified_event_star v1.6.0.
-- Engine-owned (D-09): do not edit; flag drift instead (rule 8). Spec: docs/spec/engine.md.

{{ config(materialized='table') }}

with source as (

    select * from {{ ref('silver_flights') }}
    {% if is_incremental() %}
    where captured_at >= (
        select coalesce(max(captured_at), timestamp '1900-01-01')
        from {{ this }}
    )
    {% endif %}

),

keyed as (

    select
        lower(to_json(struct_pack(
            air_time_minutes := cast(air_time_minutes as varchar),
            arr_delay_minutes := cast(arr_delay_minutes as varchar),
            dep_delay_minutes := cast(dep_delay_minutes as varchar),
            distance_miles := cast(distance_miles as varchar)
        ))) as fact_values,
        lower(to_json(struct_pack(
            aircraft_engine_type := cast(aircraft_engine_type as varchar),
            aircraft_manufacture_year := cast(aircraft_manufacture_year as varchar),
            aircraft_manufacturer := cast(aircraft_manufacturer as varchar),
            aircraft_model := cast(aircraft_model as varchar),
            aircraft_seat_count := cast(aircraft_seat_count as varchar),
            arr_hhmm := cast(arr_hhmm as varchar),
            carrier_code := cast(carrier_code as varchar),
            carrier_name := cast(carrier_name as varchar),
            dep_hhmm := cast(dep_hhmm as varchar),
            dest_airport := cast(dest_airport as varchar),
            dest_airport_name := cast(dest_airport_name as varchar),
            dest_elevation_ft := cast(dest_elevation_ft as varchar),
            dest_iso_region := cast(dest_iso_region as varchar),
            dest_longest_runway_ft := cast(dest_longest_runway_ft as varchar),
            dest_municipality := cast(dest_municipality as varchar),
            flight_date := cast(flight_date as varchar),
            flight_identity := sha256(lower(to_json(struct_pack(
                carrier_code := cast(carrier_code as varchar),
                flight_date := cast(flight_date as varchar),
                flight_number := cast(flight_number as varchar),
                origin_airport := cast(origin_airport as varchar),
                sched_dep_hhmm := cast(sched_dep_hhmm as varchar)
            )))),
            flight_number := cast(flight_number as varchar),
            is_cancelled := cast(is_cancelled as varchar),
            origin_airport := cast(origin_airport as varchar),
            origin_airport_name := cast(origin_airport_name as varchar),
            origin_elevation_ft := cast(origin_elevation_ft as varchar),
            origin_longest_runway_ft := cast(origin_longest_runway_ft as varchar),
            origin_municipality := cast(origin_municipality as varchar),
            sched_arr_hhmm := cast(sched_arr_hhmm as varchar),
            sched_dep_hhmm := cast(sched_dep_hhmm as varchar),
            sched_dep_hour_local := cast(sched_dep_hour_local as varchar),
            sched_dep_minute_local := cast(sched_dep_minute_local as varchar),
            tail_number := cast(tail_number as varchar)
        ))) as dim_payload,
        lower(to_json(struct_pack(
            grain := 'hour',
            period_start := cast(date_trunc('hour', departure_hour_utc) as varchar)
        ))) as timeframe_payload,
        captured_at
    from source

),

hashed as (

    select
        sha256(fact_values)         as fact_hash_id,
        sha256(lower(to_json(struct_pack(
                source_table := 'silver.silver_flights'
            )))) as source_hash_id,
        sha256(timeframe_payload)   as timeframe_hash_id,
        sha256(dim_payload)         as dim_hash_id,
        sha256(lower(to_json(struct_pack(
                engine_version := '0.5.0',
                mapping_contract_name := 'gold_flights_mapping',
                mapping_contract_version := '1.0.0'
            )))) as run_hash_id,
        'bbcae4efb6f4db6e756283463eb71e7052195caf2586f795317836b644bc7ddf' as fact_col_hash_id,
        fact_values,
        captured_at
    from keyed

)

select
    fact_hash_id,
    source_hash_id,
    timeframe_hash_id,
    dim_hash_id,
    run_hash_id,
    fact_col_hash_id,
    fact_values,
    current_localtimestamp()    as loaded_at,
    captured_at
from hashed
{% if is_incremental() %}
where not exists (
    select 1 from {{ this }} t
    where t.fact_hash_id = hashed.fact_hash_id
      and t.source_hash_id = hashed.source_hash_id
      and t.timeframe_hash_id = hashed.timeframe_hash_id
      and t.dim_hash_id = hashed.dim_hash_id
)
{% endif %}
