-- Generated by metricmine-engine v0.5.0 from gold_invoice_lines_mapping v1.1.1 + gold_unified_event_star v1.6.0.
-- Derivative typed projection over the star; uncontracted by design (D-17). Do not edit; flag drift instead (rule 8).

{{ config(materialized='view') }}

with f as (

    select * from {{ ref('fact_invoice_lines_values') }}

),

d as (

    select * from {{ ref('dim_invoice_lines_values') }}

),

t as (

    select * from {{ ref('dim_timeframe_values') }}

)

select
    cast(json_extract_string(d.dim_values, '$.invoice_id') as VARCHAR) as invoice_id,
    cast(json_extract_string(d.dim_values, '$.is_cancellation') as BOOLEAN) as is_cancellation,
    cast(json_extract_string(d.dim_values, '$.stock_code') as VARCHAR) as stock_code,
    cast(json_extract_string(d.dim_values, '$.product_description') as VARCHAR) as product_description,
    cast(json_extract_string(d.dim_values, '$.customer_id') as INTEGER) as customer_id,
    cast(json_extract_string(d.dim_values, '$.country') as VARCHAR) as country,
    cast(json_extract_string(d.dim_values, '$.line_identity') as VARCHAR) as line_identity,
    cast(json_extract_string(t.timeframe_values, '$.period_start') as TIMESTAMP) as invoiced_at,
    cast(json_extract_string(f.fact_values, '$.quantity') as INTEGER) as quantity,
    cast(json_extract_string(f.fact_values, '$.unit_price') as DECIMAL(10,2)) as unit_price
from f
join d on d.dim_hash_id = f.dim_hash_id
join t on t.timeframe_hash_id = f.timeframe_hash_id
